Restart sshd in Alpine init

diff --git a/PREFIX/src/roles/init/script b/PREFIX/src/roles/init/script
--- a/PREFIX/src/roles/init/script
+++ b/PREFIX/src/roles/init/script
@@ -77,6 +77,7 @@ else
             sudo systemctl reload sshd
         elif exists apk; then
             sudo apk -q add openssh sudo
+            sudo rc-service sshd restart || true #Fails in WSL
         elif exists apt-get; then
             sudo apt-get install -qy openssh-server sudo
             sudo systemctl enable --now ssh
