Merge website and ssl roles

diff --git a/PREFIX/src/roles/website/script b/PREFIX/src/roles/website/script
--- a/PREFIX/src/roles/website/script
+++ b/PREFIX/src/roles/website/script
@@ -2,9 +2,11 @@
 #website - set up website with nginx or apache
 set -eu
 
+die() { printf '%s\n' "$*" >&2; exit 1; }
 echo() { printf "%s" "$*"; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 in_dir() ( cd "$1"; shift; "$@"; )
+sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; sudo mv "$2" "$1"; }
 
 lineinfile() { #1: path, 2: regexp, 3: line
     [ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
@@ -30,7 +32,6 @@ PORT="${PORT:-$( \
     echo "$BASE_URL" | sed -E 's_(https?://)?[^/:]*(:([0-8]*))?.*_\3_')}" \
 FILENAME="$FQDN${PORT:+:$PORT}"
 LOCATION="${LOCATION:-/srv/http/$FILENAME}"
-PORT="${PORT:-80}"
 
 if [ "$TEMPLATE" = reverseproxy ]; then
     : "$PROXY_PASS" #error if unset
@@ -60,7 +61,7 @@ apache)
     in_dir "/etc/$DAEMON/templates" cat "$TEMPLATE" \
         | sed \
             -e "s/\\\$FQDN/$FQDN/" \
-            -e "s/\\\$PORT/$PORT/" \
+            -e "s/\\\$PORT/${PORT:-80}/" \
             -e "s \\\$LOCATION $LOCATION " \
         | sudo tee "/etc/$DAEMON/sites/$FILENAME.conf" >/dev/null
     cat "/etc/$DAEMON/sites/"*.conf \
@@ -74,7 +75,7 @@ nginx)
     in_dir "/etc/nginx/templates" cat "$TEMPLATE" \
         | sed \
             -e "s/\\\$FQDN/$FQDN/" \
-            -e "s/\\\$PORT/$PORT/" \
+            -e "s/\\\$PORT/${PORT:-80}/" \
             -e "s \\\$PROXY_PASS ${PROXY_PASS-gimme_an_error} " \
             -e "s \\\$FASTCGI_PASS ${FASTCGI_PASS-gimme_an_error} " \
             -e "s \\\$LOCATION $LOCATION " \
@@ -83,3 +84,33 @@ nginx)
     ;;
 esac
 
+if "$SSL"; then
+    echo "$FQDN" | grep -qF . || die "ERROR: Invalid FQDN"
+    case "${HTTPD-nginx}" in
+    nginx)
+        if exists apt-get; then
+            sudo apt-get install -yq software-properties-common
+            sudo add-apt-repository universe
+            sudo apt-get update
+            sudo apt-get install -yq certbot python3-certbot-nginx
+        elif exists pacman; then
+            sudo pacman -qS --needed --noconfirm certbot-nginx
+        fi
+        if sudo test ! -d "/etc/letsencrypt/live/$FQDN"; then
+            sudo certbot certonly -n --nginx --agree-tos --no-eff-email \
+                -m "root@$FQDN" -d "$FQDN" --cert-name "$FQDN"
+        fi
+        sudo certbot install -n --nginx --reinstall -d "$FQDN" \
+            --cert-name "$FQDN"
+        <"/etc/nginx/sites/$FILENAME.conf" \
+            sed 's/\(443\|'"${PORT:-443}"'\) ssl\( http2\|\);/'"$(
+                    )${PORT:-443}"' ssl http2;/' \
+                | sponge "/etc/nginx/sites/$FILENAME.conf"
+        sudo systemctl reload nginx || sudo systemctl restart nginx || true
+        sudo systemctl enable --now certbot-renew.timer
+        ;;
+    *)
+        die "ERROR: SSL installation not implemented for $HTTPD"
+        ;;
+    esac
+fi
