Add Tailscale ssl to website role

diff --git a/PREFIX/src/roles/website/script b/PREFIX/src/roles/website/script
--- a/PREFIX/src/roles/website/script
+++ b/PREFIX/src/roles/website/script
@@ -104,8 +104,29 @@ esac
 
 if "${SSL:-false}"; then
     echo "$FQDN" | grep -qF . || die "ERROR: Invalid FQDN"
-    case "${HTTPD-nginx}" in
-    nginx)
+    [ "${HTTPD:-nginx}" = nginx ] \
+        || die "ERROR: SSL installation not implemented for $HTTPD"
+    case "$FQDN" in
+    *.ts.net)
+        sudo mkdir -p /etc/nginx/ssl/
+        sudo tailscale cert --cert-file "/etc/nginx/ssl/$FQDN.crt" \
+            --key-file "/etc/nginx/ssl/$FQDN.key" "$FQDN"
+        echo "tailscale"
+        if ! grep ssl_certificate "/etc/nginx/sites/$FILENAME.conf" >/dev/null; then
+            printf "%s\n" \
+                    "server {" \
+                    "    server_name \"$FQDN\";" \
+                    "    listen 443 ssl;" \
+                    "    listen [::]:443 ssl;" \
+                    "    http2 on;" \
+                    "    ssl_certificate \"/etc/nginx/ssl/$FQDN.crt\";" \
+                    "    ssl_certificate_key \"/etc/nginx/ssl/$FQDN.key\";" \
+                    "    include sites/$FILENAME.d/*.conf;" \
+                    "}" \
+                | sudo tee -a "/etc/nginx/sites/$FILENAME.conf"
+        fi
+        ;;
+    *)
         if exists apt-get; then
             sudo apt-get install -yq software-properties-common
             sudo add-apt-repository universe
@@ -125,9 +146,6 @@ if "${SSL:-false}"; then
                     )${PORT:-443}"' ssl http2;/' \
                 | sponge "/etc/nginx/sites/$FILENAME.conf"
         sudo systemctl enable --now certbot-renew.timer
-        ;;
-    *)
-        die "ERROR: SSL installation not implemented for $HTTPD"
         ;;
     esac
     sudo systemctl reload nginx || sudo systemctl restart nginx || true
