Format with tabs

diff --git a/PREFIX/src/roles/home b/PREFIX/src/roles/home
--- a/PREFIX/src/roles/home
+++ b/PREFIX/src/roles/home
@@ -7,36 +7,36 @@ exists() { command -v "$1" >/dev/null 2>&1; }
 in_dir() (cd "$1" && shift && "$@")
 
 if exists apk; then
-    sudo apk add -q curl git git-perl gnupg make ncurses zsh
+	sudo apk add -q curl git git-perl gnupg make ncurses zsh
 elif exists apt-get; then
-    sudo apt-get install -yq curl git gnupg make zsh
+	sudo apt-get install -yq curl git gnupg make zsh
 elif exists brew; then
-    brew install gnupg
+	brew install gnupg
 elif exists pacman; then
-    sudo pacman --needed --noconfirm -qS git gnupg make zsh
+	sudo pacman --needed --noconfirm -qS git gnupg make zsh
 fi
 
 if exists zsh && [ "$SHELL" != "$(command -v zsh)" ]; then
-    </etc/passwd sed "/^mil:/s_:/[^:]*\$_:$(command -v zsh)_" \
-        | sudo tee /etc/passwd.new >/dev/null
-    sudo mv /etc/passwd.new /etc/passwd
-    sudo chmod og-wx /etc/passwd
+	</etc/passwd sed "/^mil:/s_:/[^:]*\$_:$(command -v zsh)_" \
+		| sudo tee /etc/passwd.new >/dev/null
+	sudo mv /etc/passwd.new /etc/passwd
+	sudo chmod og-wx /etc/passwd
 fi
 
 #Set env
 set -a
 case "$(uname -s)" in
 Darwin)
-    PREFIX="$HOME/Library/Local"
-    XDG_CACHE_HOME="$HOME/Library/Caches"
-    XDG_CONFIG_HOME="$HOME/Library/Application Support"
-    MACOS_LIBRARY="$HOME/Library"
-    ;;
+	PREFIX="$HOME/Library/Local"
+	XDG_CACHE_HOME="$HOME/Library/Caches"
+	XDG_CONFIG_HOME="$HOME/Library/Application Support"
+	MACOS_LIBRARY="$HOME/Library"
+	;;
 Linux)
-    PREFIX="$HOME/.local"
-    XDG_CACHE_HOME="$HOME/.cache"
-    XDG_CONFIG_HOME="$HOME/.config"
-    ;;
+	PREFIX="$HOME/.local"
+	XDG_CACHE_HOME="$HOME/.cache"
+	XDG_CONFIG_HOME="$HOME/.config"
+	;;
 esac
 XDG_DATA_HOME="$PREFIX/share"
 XDG_BIN_HOME="$PREFIX/bin"
@@ -45,18 +45,18 @@ TERMINFO="$XDG_DATA_HOME/terminfo"
 
 #Install terminfo for alacritty
 if ! infocmp alacritty >/dev/null 2>&1; then
-    alacritty_info="$(mktemp)"
-    curl "$(printf "%s%s" 'https://raw.githubusercontent.com' \
-        '/jwilm/alacritty/master/extra/alacritty.info')" >"$alacritty_info"
-    tic -xe alacritty,alacritty-direct "$alacritty_info"
-    rm -rf "$alacritty_info" "$HOME/.terminfo"
+	alacritty_info="$(mktemp)"
+	curl "$(printf "%s%s" 'https://raw.githubusercontent.com' \
+		'/jwilm/alacritty/master/extra/alacritty.info')" >"$alacritty_info"
+	tic -xe alacritty,alacritty-direct "$alacritty_info"
+	rm -rf "$alacritty_info" "$HOME/.terminfo"
 fi
 
 #Clone dotfiles and install
 [ -d "${DOTFILES-$PREFIX/dot}" ] \
-    || git clone https://milhnl@github.com/milhnl/dotfiles \
-        "${DOTFILES-$PREFIX/dot}" \
-    || die "Repository with dotfiles is missing"
+	|| git clone https://milhnl@github.com/milhnl/dotfiles \
+		"${DOTFILES-$PREFIX/dot}" \
+	|| die "Repository with dotfiles is missing"
 
 in_dir "${DOTFILES-$PREFIX/dot}" make link
 
diff --git a/PREFIX/src/roles/init b/PREFIX/src/roles/init
--- a/PREFIX/src/roles/init
+++ b/PREFIX/src/roles/init
@@ -6,58 +6,58 @@ die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 getsh() { command -v zsh || command -v bash || command -v ash || echo sh; }
 lineinfile() {
-    sudo grep -qxF "$2" "$1" || echo "$2" | sudo tee -a "$1" >/dev/null
+	sudo grep -qxF "$2" "$1" || echo "$2" | sudo tee -a "$1" >/dev/null
 }
 [ $(id -u) = 0 ] && ! exists sudo && sudo() { "$@"; } || true #just run as root
 rndpasswd() {
-    { LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 2>/dev/null || :; } \
-        | head -c64 \
-        | sed p \
-        | sudo passwd "${1:-root}" >/dev/null 2>&1 \
-        || die "Can't lock password for ${1:-root}"
+	{ LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 2>/dev/null || :; } \
+		| head -c64 \
+		| sed p \
+		| sudo passwd "${1:-root}" >/dev/null 2>&1 \
+		|| die "Can't lock password for ${1:-root}"
 }
 
 #Initialize package managers
 case "$(uname -s)" in
 Darwin)
-    URL="https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
-    if ! exists brew; then
-        bash -c "$(curl -fsSL "$URL")" || die "Homebrew installation failed"
-    fi
-    ;;
+	URL="https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
+	if ! exists brew; then
+		bash -c "$(curl -fsSL "$URL")" || die "Homebrew installation failed"
+	fi
+	;;
 Linux)
-    if exists apk; then
-        sudo apk update
-    elif exists apt-get; then
-        sudo apt-get update
-    elif exists opkg; then
-        sudo opkg update
-    elif exists pacman; then
-        sudo pacman-key --init
-        sudo pacman-key --populate \
-            "archlinux$(uname -m | sed -n 's/\(armv[67]l\|aarch64\)/arm/p')"
-        sudo sed -i '/ParallelDownloads/s/^#//g' /etc/pacman.conf
-        sudo pacman --noconfirm --needed -qSyu
-    fi
-    ;;
+	if exists apk; then
+		sudo apk update
+	elif exists apt-get; then
+		sudo apt-get update
+	elif exists opkg; then
+		sudo opkg update
+	elif exists pacman; then
+		sudo pacman-key --init
+		sudo pacman-key --populate \
+			"archlinux$(uname -m | sed -n 's/\(armv[67]l\|aarch64\)/arm/p')"
+		sudo sed -i '/ParallelDownloads/s/^#//g' /etc/pacman.conf
+		sudo pacman --noconfirm --needed -qSyu
+	fi
+	;;
 esac
 
 #Create user
 if ! id -u mil >/dev/null 2>&1; then
-    if exists opkg; then
-        sudo opkg install shadow-useradd shadow-groupadd
-    elif exists uci && exists apk; then
-        sudo apk add shadow-useradd shadow-groupadd
-    fi
-    if exists useradd; then
-        sudo groupadd wheel || sudo grep -qw '^wheel' /etc/group \
-            || die "Can't add user to wheel"
-        sudo useradd -G wheel -s "$(getsh)" -m mil
-    elif exists adduser; then
-        sudo adduser -G wheel -s "$(getsh)" -D mil
-    fi
-    id -u mil >/dev/null 2>&1 || die "Can't add user mil"
-    rndpasswd mil
+	if exists opkg; then
+		sudo opkg install shadow-useradd shadow-groupadd
+	elif exists uci && exists apk; then
+		sudo apk add shadow-useradd shadow-groupadd
+	fi
+	if exists useradd; then
+		sudo groupadd wheel || sudo grep -qw '^wheel' /etc/group \
+			|| die "Can't add user to wheel"
+		sudo useradd -G wheel -s "$(getsh)" -m mil
+	elif exists adduser; then
+		sudo adduser -G wheel -s "$(getsh)" -D mil
+	fi
+	id -u mil >/dev/null 2>&1 || die "Can't add user mil"
+	rndpasswd mil
 fi
 
 #Copy ssh public key and fix all permissions
@@ -73,127 +73,127 @@ EOF
 sudo chown -R mil ~mil/.ssh
 sudo chown mil ~mil
 if </etc/group grep -q '^mil:'; then
-    sudo chgrp -R mil ~mil/.ssh
-    sudo chgrp mil ~mil
+	sudo chgrp -R mil ~mil/.ssh
+	sudo chgrp mil ~mil
 fi
 sudo chmod -R og-rwxs ~mil/.ssh
 sudo chmod og-rwxs ~mil
 
 #Install and configure sshd/dropbear
 if exists uci; then
-    if exists opkg; then
-        sudo opkg install sudo openssh-sftp-server
-    elif exists apk; then
-        sudo apk add sudo openssh-sftp-server
-    fi
-    lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
-    sudo rm -f /etc/banner
-    sudo uci set 'dropbear.@dropbear[0].RootPasswordAuth=off'
-    sudo uci set 'dropbear.@dropbear[0].PasswordAuth=off'
-    sudo uci commit dropbear
-    sudo /etc/init.d/dropbear restart
+	if exists opkg; then
+		sudo opkg install sudo openssh-sftp-server
+	elif exists apk; then
+		sudo apk add sudo openssh-sftp-server
+	fi
+	lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
+	sudo rm -f /etc/banner
+	sudo uci set 'dropbear.@dropbear[0].RootPasswordAuth=off'
+	sudo uci set 'dropbear.@dropbear[0].PasswordAuth=off'
+	sudo uci commit dropbear
+	sudo /etc/init.d/dropbear restart
 else
-    mkdir -p /etc/ssh
-    { sed "s/^  *//;$(sudo sshd -T 2>/dev/null | grep -iq UsePAM \
-        || echo '/UsePAM/d')" \
-        | sudo tee /etc/ssh/sshd_config >/dev/null; } <<"    EOF"
-        PermitRootLogin no
-        AuthorizedKeysFile .ssh/authorized_keys
-        PasswordAuthentication no
-        ChallengeResponseAuthentication no
-        UsePAM yes
-        PrintMotd no # pam does that
-        GatewayPorts yes
-        StreamLocalBindUnlink yes
-        AcceptEnv TERM_PROGRAM
-    EOF
-    { if [ "$(uname -s)" = Darwin ]; then
-        echo 'Subsystem sftp internal-sftp'
-    elif [ -e /usr/lib/openssh/sftp-server ]; then
-        echo 'Subsystem sftp /usr/lib/openssh/sftp-server'
-    elif [ -e /usr/lib/ssh/sftp-server ]; then
-        echo 'Subsystem sftp /usr/lib/ssh/sftp-server'
-    fi; } | sudo tee -a /etc/ssh/sshd_config >>/dev/null
-    case "$(uname -s)" in
-    Darwin)
-        sudo systemsetup -f -setremotelogin on
-        lineinfile /etc/sudoers '%admin ALL=(ALL) NOPASSWD: ALL'
-        ;;
-    Linux)
-        if grep -iq microsoft /proc/version 2>/dev/null; then
-            if exists apk; then
-                sudo apk -q add openssh sudo
-            elif exists apt-get; then
-                DEBIAN_FRONTEND=noninteractive apt-get -yq install \
-                    openssh-server sudo
-            fi
-            sudo pkill sshd || :
-            mkdir -p /run/sshd
-            sudo ssh-keygen -A
-            sudo /usr/sbin/sshd -p 23
-        elif exists pacman; then
-            sudo pacman --needed --noconfirm -qS openssh sudo
-            if ! "${CHROOT:-false}"; then
-                sudo systemctl enable --now sshd
-                sudo systemctl reload sshd
-            else
-                sudo systemctl enable sshd
-            fi
-        elif exists apk; then
-            sudo apk -q add openssh sudo
-            sudo rc-service sshd restart
-        elif exists apt-get; then
-            sudo apt-get install -qy openssh-server sudo
-            sudo systemctl enable --now ssh
-            sudo systemctl reload ssh
-        fi
-        lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
-        unset -f sudo
-        exists sudo && ps -A 2>/dev/null | grep -q sshd \
-            || "${CHROOT:-false}" \
-            || die "sudo/ssh setup failed"
-        ;;
-    esac
+	mkdir -p /etc/ssh
+	{ sed "s/^  *//;$(sudo sshd -T 2>/dev/null | grep -iq UsePAM \
+		|| echo '/UsePAM/d')" \
+		| sudo tee /etc/ssh/sshd_config >/dev/null; } <<-EOF
+			PermitRootLogin no
+			AuthorizedKeysFile .ssh/authorized_keys
+			PasswordAuthentication no
+			ChallengeResponseAuthentication no
+			UsePAM yes
+			PrintMotd no # pam does that
+			GatewayPorts yes
+			StreamLocalBindUnlink yes
+			AcceptEnv TERM_PROGRAM
+		EOF
+	{ if [ "$(uname -s)" = Darwin ]; then
+		echo 'Subsystem sftp internal-sftp'
+	elif [ -e /usr/lib/openssh/sftp-server ]; then
+		echo 'Subsystem sftp /usr/lib/openssh/sftp-server'
+	elif [ -e /usr/lib/ssh/sftp-server ]; then
+		echo 'Subsystem sftp /usr/lib/ssh/sftp-server'
+	fi; } | sudo tee -a /etc/ssh/sshd_config >>/dev/null
+	case "$(uname -s)" in
+	Darwin)
+		sudo systemsetup -f -setremotelogin on
+		lineinfile /etc/sudoers '%admin ALL=(ALL) NOPASSWD: ALL'
+		;;
+	Linux)
+		if grep -iq microsoft /proc/version 2>/dev/null; then
+			if exists apk; then
+				sudo apk -q add openssh sudo
+			elif exists apt-get; then
+				DEBIAN_FRONTEND=noninteractive apt-get -yq install \
+					openssh-server sudo
+			fi
+			sudo pkill sshd || :
+			mkdir -p /run/sshd
+			sudo ssh-keygen -A
+			sudo /usr/sbin/sshd -p 23
+		elif exists pacman; then
+			sudo pacman --needed --noconfirm -qS openssh sudo
+			if ! "${CHROOT:-false}"; then
+				sudo systemctl enable --now sshd
+				sudo systemctl reload sshd
+			else
+				sudo systemctl enable sshd
+			fi
+		elif exists apk; then
+			sudo apk -q add openssh sudo
+			sudo rc-service sshd restart
+		elif exists apt-get; then
+			sudo apt-get install -qy openssh-server sudo
+			sudo systemctl enable --now ssh
+			sudo systemctl reload ssh
+		fi
+		lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
+		unset -f sudo
+		exists sudo && ps -A 2>/dev/null | grep -q sshd \
+			|| "${CHROOT:-false}" \
+			|| die "sudo/ssh setup failed"
+		;;
+	esac
 fi
 [ "$(uname -s)" = Darwin ] || rndpasswd root
 
 #Set hostname
 if [ -n "${NEWHOSTNAME-}" ]; then
-    HOSTNAME="$NEWHOSTNAME"
+	HOSTNAME="$NEWHOSTNAME"
 else
-    HOSTNAME="${HOSTNAME-$(uname -n)}"
+	HOSTNAME="${HOSTNAME-$(uname -n)}"
 fi
 if ! expr localhost = "$HOSTNAME" \| "$HOSTNAME" : '[0-9.]*$' >/dev/null; then
-    echo "$HOSTNAME" | sed 's/\..*//' | sudo tee /etc/hostname >/dev/null
-    if [ "$(uname -s)" = Darwin ]; then
-        for name in HostName LocalHostName ComputerName; do
-            sudo scutil --set "$name" "$HOSTNAME"
-        done
-        sudo dscacheutil -flushcache
-    elif exists uci; then
-        sudo uci set "system.@system[0].hostname=$HOSTNAME"
-        sudo uci commit system
-    elif [ -d /etc/conf.d ]; then
-        echo "hostname='$HOSTNAME'" | sudo tee /etc/conf.d/hostname >/dev/null
-    fi
-    if [ -f /etc/dhcpcd.conf ]; then
-        lineinfile /etc/dhcpcd.conf hostname
-    fi
+	echo "$HOSTNAME" | sed 's/\..*//' | sudo tee /etc/hostname >/dev/null
+	if [ "$(uname -s)" = Darwin ]; then
+		for name in HostName LocalHostName ComputerName; do
+			sudo scutil --set "$name" "$HOSTNAME"
+		done
+		sudo dscacheutil -flushcache
+	elif exists uci; then
+		sudo uci set "system.@system[0].hostname=$HOSTNAME"
+		sudo uci commit system
+	elif [ -d /etc/conf.d ]; then
+		echo "hostname='$HOSTNAME'" | sudo tee /etc/conf.d/hostname >/dev/null
+	fi
+	if [ -f /etc/dhcpcd.conf ]; then
+		lineinfile /etc/dhcpcd.conf hostname
+	fi
 fi
 
 if exists systemctl && systemctl is-enabled -q systemd-resolved; then
-    sudo mkdir -p "/etc/systemd/resolved.conf.d/"
-    printf '[Resolve]\nResolveUnicastSingleLabel=yes\n' \
-        | sudo tee /etc/systemd/resolved.conf.d/resolve-lan.conf >/dev/null
+	sudo mkdir -p "/etc/systemd/resolved.conf.d/"
+	printf '[Resolve]\nResolveUnicastSingleLabel=yes\n' \
+		| sudo tee /etc/systemd/resolved.conf.d/resolve-lan.conf >/dev/null
 fi
 
 #Synchronise time
 if exists pacman; then
-    sudo pacman --noconfirm --needed -qS ntp
-    sudo systemctl enable $(${CHROOT:-false} || printf '%s' --now) ntpd
+	sudo pacman --noconfirm --needed -qS ntp
+	sudo systemctl enable $(${CHROOT:-false} || printf '%s' --now) ntpd
 fi
 
 #Remove set-up user
 if id -u alarm >/dev/null 2>&1; then
-    sudo userdel -f alarm >/dev/null 2>&1
+	sudo userdel -f alarm >/dev/null 2>&1
 fi
diff --git a/PREFIX/src/roles/user b/PREFIX/src/roles/user
--- a/PREFIX/src/roles/user
+++ b/PREFIX/src/roles/user
@@ -8,37 +8,37 @@ die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 get_user_home() { eval "echo ~$(echo "$1" | sed 's/[^-A-Za-z0-9.]/\\&/g')"; }
 
 rndpasswd() {
-    LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 \
-        | head -c64 \
-        | sed p \
-        | sudo passwd "${1:-root}" >/dev/null 2>&1 \
-        || die "Can't lock password for ${1:-root}"
+	LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 \
+		| head -c64 \
+		| sed p \
+		| sudo passwd "${1:-root}" >/dev/null 2>&1 \
+		|| die "Can't lock password for ${1:-root}"
 }
 
 USER_SHELL="${USER_SHELL:-/bin/false}"
 
 if ! id -u "$USER_NAME" >/dev/null 2>&1; then
-    if exists useradd; then
-        sudo useradd -s "$(command -v "$USER_SHELL")" -m "$USER_NAME"
-    elif exists adduser; then
-        sudo adduser -s "$(command -v "$USER_SHELL")" -D "$USER_NAME"
-    fi
+	if exists useradd; then
+		sudo useradd -s "$(command -v "$USER_SHELL")" -m "$USER_NAME"
+	elif exists adduser; then
+		sudo adduser -s "$(command -v "$USER_SHELL")" -D "$USER_NAME"
+	fi
 fi
 rndpasswd "$USER_NAME"
 
 if [ -n "${USER_PUBKEY:-}" ] && [ -d "$(get_user_home "$USER_NAME")" ]; then
-    sudo mkdir -p "$(get_user_home "$USER_NAME")/.ssh"
-    echo "$USER_PUBKEY" \
-        | sudo tee "$(get_user_home "$USER_NAME")/.ssh/authorized_keys" \
-            >/dev/null
-    sudo chown -R "$USER_NAME" "$(get_user_home "$USER_NAME")/.ssh"
-    sudo chown "$USER_NAME" "$(get_user_home "$USER_NAME")"
-    if getent group "$USER_NAME" >/dev/null \
-        || </etc/group grep -q "^$USER_NAME:"; then
-        sudo chgrp -R "$USER_NAME" "$(get_user_home "$USER_NAME")/.ssh"
-        sudo chgrp "$USER_NAME" "$(get_user_home "$USER_NAME")"
-    fi
-    sudo chmod -R og-rwxs "$(get_user_home "$USER_NAME")/.ssh"
-    sudo chmod og-rwxs "$(get_user_home "$USER_NAME")"
+	sudo mkdir -p "$(get_user_home "$USER_NAME")/.ssh"
+	echo "$USER_PUBKEY" \
+		| sudo tee "$(get_user_home "$USER_NAME")/.ssh/authorized_keys" \
+			>/dev/null
+	sudo chown -R "$USER_NAME" "$(get_user_home "$USER_NAME")/.ssh"
+	sudo chown "$USER_NAME" "$(get_user_home "$USER_NAME")"
+	if getent group "$USER_NAME" >/dev/null \
+		|| </etc/group grep -q "^$USER_NAME:"; then
+		sudo chgrp -R "$USER_NAME" "$(get_user_home "$USER_NAME")/.ssh"
+		sudo chgrp "$USER_NAME" "$(get_user_home "$USER_NAME")"
+	fi
+	sudo chmod -R og-rwxs "$(get_user_home "$USER_NAME")/.ssh"
+	sudo chmod og-rwxs "$(get_user_home "$USER_NAME")"
 
 fi
diff --git a/PREFIX/src/roles/website/script b/PREFIX/src/roles/website/script
--- a/PREFIX/src/roles/website/script
+++ b/PREFIX/src/roles/website/script
@@ -9,146 +9,146 @@ in_dir() (cd "$1" && shift && "$@")
 sponge() { set -- "$1" "$(mktemp)" && cat >"$2" && sudo mv "$2" "$1"; }
 
 lineinfile() { #1: path, 2: regexp, 3: line
-    [ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
-    if grep -qF "^$3$" "$1" 2>/dev/null; then
-        return
-    elif grep -q "$2" "$1" 2>/dev/null; then
-        set -- "$1" "$2" "$3" "$(mktemp)"
-        <"$1" sed "s/.*$(echo "$2" | sed 's_/_\\/_').*/$(
-        )$(echo "$3" | sed 's_/_\\/_')/" >"$4"
-        sudo mv "$4" "$1"
-    else
-        sudo sh -c 'echo "$3" >>"$1"' - "$@"
-    fi
+	[ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
+	if grep -qF "^$3$" "$1" 2>/dev/null; then
+		return
+	elif grep -q "$2" "$1" 2>/dev/null; then
+		set -- "$1" "$2" "$3" "$(mktemp)"
+		<"$1" sed "s/.*$(echo "$2" | sed 's_/_\\/_').*/$(
+		)$(echo "$3" | sed 's_/_\\/_')/" >"$4"
+		sudo mv "$4" "$1"
+	else
+		sudo sh -c 'echo "$3" >>"$1"' - "$@"
+	fi
 }
 
 TEMPLATE="${TEMPLATE:-static}"
 FQDN="${FQDN:-$([ -z "${BASE_URL-}" ] \
-    || echo "$BASE_URL" | sed -E 's_(https?://)?([^/:]*).*_\2_')}"
+	|| echo "$BASE_URL" | sed -E 's_(https?://)?([^/:]*).*_\2_')}"
 URL_PREFIX="${URL_PREFIX:-$([ -z "${BASE_URL-}" ] \
-    || echo "$BASE_URL" | sed -E 's_(https?://)?([^/]*)/?__')}"
+	|| echo "$BASE_URL" | sed -E 's_(https?://)?([^/]*)/?__')}"
 PORT="${PORT:-$(
-    echo "${BASE_URL-}" | sed -E 's_(https?://)?[^/:]*(:([0-8]*))?.*_\3_'
+	echo "${BASE_URL-}" | sed -E 's_(https?://)?[^/:]*(:([0-8]*))?.*_\3_'
 )}"
 FILENAME="${FQDN:-localhost}${PORT:+:$PORT}"
 LOCATION="${LOCATION:-/srv/http/$FILENAME}"
 LEVEL="${LEVEL:-$([ -n "$URL_PREFIX" ] && echo location || echo server)}"
 
 if [ "$TEMPLATE" = reverseproxy ]; then
-    : "$PROXY_PASS" #error if unset
+	: "$PROXY_PASS" #error if unset
 elif [ "$TEMPLATE" = php ]; then
-    sudo pacman --needed --noconfirm -qS php-fpm
-    sudo systemctl enable --now php-fpm
-    FASTCGI_PASS=unix:/run/php-fpm/php-fpm.sock
+	sudo pacman --needed --noconfirm -qS php-fpm
+	sudo systemctl enable --now php-fpm
+	FASTCGI_PASS=unix:/run/php-fpm/php-fpm.sock
 elif [ "$TEMPLATE" = php7 ]; then
-    sudo pacman --needed --noconfirm -qS php7-fpm
-    sudo systemctl enable --now php-fpm7
-    FASTCGI_PASS=unix:/run/php-fpm7/php-fpm.sock
-    TEMPLATE=php
+	sudo pacman --needed --noconfirm -qS php7-fpm
+	sudo systemctl enable --now php-fpm7
+	FASTCGI_PASS=unix:/run/php-fpm7/php-fpm.sock
+	TEMPLATE=php
 elif [ "$TEMPLATE" = static ] || [ "$TEMPLATE" = static-protected ]; then
-    sudo mkdir -p "$LOCATION"
+	sudo mkdir -p "$LOCATION"
 fi
 
 case "${HTTPD-nginx}" in
 apache)
-    if exists pacman; then
-        DAEMON=httpd
-    elif exists apt-get; then
-        DAEMON=apache2
-    fi
-    [ "$TEMPLATE" = php ] && TEMPLATE=static || :
-    sudo mkdir -p "/etc/$DAEMON/templates/"
-    sudo cp "website/apache-templates"/* "/etc/$DAEMON/templates/"
-    in_dir "/etc/$DAEMON/templates" cat "$TEMPLATE" \
-        | sed \
-            -e "s/\\\$FQDN/$FQDN/" \
-            -e "s/\\\$PORT/${PORT:-80}/" \
-            -e "s \\\$LOCATION $LOCATION " \
-        | sudo tee "/etc/$DAEMON/sites/$FILENAME.conf" >/dev/null
-    cat "/etc/$DAEMON/sites/"*.conf \
-        | sed -n 's/<VirtualHost [^: \/]*:\([0-9]*\)>.*/Listen \1/p' \
-        | sudo tee "/etc/$DAEMON/ports.conf" >/dev/null
-    sudo systemctl restart "$DAEMON"
-    ;;
+	if exists pacman; then
+		DAEMON=httpd
+	elif exists apt-get; then
+		DAEMON=apache2
+	fi
+	[ "$TEMPLATE" = php ] && TEMPLATE=static || :
+	sudo mkdir -p "/etc/$DAEMON/templates/"
+	sudo cp "website/apache-templates"/* "/etc/$DAEMON/templates/"
+	in_dir "/etc/$DAEMON/templates" cat "$TEMPLATE" \
+		| sed \
+			-e "s/\\\$FQDN/$FQDN/" \
+			-e "s/\\\$PORT/${PORT:-80}/" \
+			-e "s \\\$LOCATION $LOCATION " \
+		| sudo tee "/etc/$DAEMON/sites/$FILENAME.conf" >/dev/null
+	cat "/etc/$DAEMON/sites/"*.conf \
+		| sed -n 's/<VirtualHost [^: \/]*:\([0-9]*\)>.*/Listen \1/p' \
+		| sudo tee "/etc/$DAEMON/ports.conf" >/dev/null
+	sudo systemctl restart "$DAEMON"
+	;;
 nginx)
-    [ "$LEVEL" = server ] || sudo mkdir -p "/etc/nginx/sites/$FILENAME.d"
-    sudo mkdir -p "/etc/nginx/templates/"
-    sudo cp "website/nginx-templates"/* "/etc/nginx/templates/"
-    in_dir "/etc/nginx/templates" cat "$TEMPLATE" \
-        | if [ "$LEVEL" = server ]; then
-            printf "%s\n" \
-                "server {" \
-                "    server_name \"$FQDN\";" \
-                "    listen ${PORT:-80};" \
-                "    include sites/$FILENAME.d/*.conf;"
-            cat
-            printf "}\n"
-        else
-            cat
-        fi \
-        | sed \
-            -e "s/\\\$FILENAME/$FILENAME/" \
-            -e "s \\\$URL_PREFIX ${URL_PREFIX} " \
-            -e "s/\\\$FQDN/$FQDN/" \
-            -e "s/\\\$PORT/${PORT:-80}/" \
-            -e "s \\\$PROXY_PASS ${PROXY_PASS-gimme_an_error} " \
-            -e "s \\\$FASTCGI_PASS ${FASTCGI_PASS-gimme_an_error} " \
-            -e "s \\\$LOCATION $LOCATION " \
-        | sudo tee "/etc/nginx/sites/$([ "$LEVEL" = server ] \
-            && echo "$FILENAME" \
-            || echo "$FILENAME.d/$URL_PREFIX").conf" >/dev/null
-    sudo systemctl reload nginx || sudo systemctl restart nginx \
-        || ! sudo systemctl is-failed nginx >/dev/null
-    ;;
+	[ "$LEVEL" = server ] || sudo mkdir -p "/etc/nginx/sites/$FILENAME.d"
+	sudo mkdir -p "/etc/nginx/templates/"
+	sudo cp "website/nginx-templates"/* "/etc/nginx/templates/"
+	in_dir "/etc/nginx/templates" cat "$TEMPLATE" \
+		| if [ "$LEVEL" = server ]; then
+			printf "%s\n" \
+				"server {" \
+				"    server_name \"$FQDN\";" \
+				"    listen ${PORT:-80};" \
+				"    include sites/$FILENAME.d/*.conf;"
+			cat
+			printf "}\n"
+		else
+			cat
+		fi \
+		| sed \
+			-e "s/\\\$FILENAME/$FILENAME/" \
+			-e "s \\\$URL_PREFIX ${URL_PREFIX} " \
+			-e "s/\\\$FQDN/$FQDN/" \
+			-e "s/\\\$PORT/${PORT:-80}/" \
+			-e "s \\\$PROXY_PASS ${PROXY_PASS-gimme_an_error} " \
+			-e "s \\\$FASTCGI_PASS ${FASTCGI_PASS-gimme_an_error} " \
+			-e "s \\\$LOCATION $LOCATION " \
+		| sudo tee "/etc/nginx/sites/$([ "$LEVEL" = server ] \
+			&& echo "$FILENAME" \
+			|| echo "$FILENAME.d/$URL_PREFIX").conf" >/dev/null
+	sudo systemctl reload nginx || sudo systemctl restart nginx \
+		|| ! sudo systemctl is-failed nginx >/dev/null
+	;;
 esac
 
 if "${SSL:-false}"; then
-    echo "$FQDN" | grep -qF . || die "ERROR: Invalid FQDN"
-    [ "${HTTPD:-nginx}" = nginx ] \
-        || die "ERROR: SSL installation not implemented for $HTTPD"
-    case "$FQDN" in
-    *.ts.net)
-        sudo mkdir -p /etc/nginx/ssl/
-        sudo tailscale cert --cert-file "/etc/nginx/ssl/$FQDN.crt" \
-            --key-file "/etc/nginx/ssl/$FQDN.key" "$FQDN"
-        echo "tailscale"
-        if ! grep ssl_certificate "/etc/nginx/sites/$FILENAME.conf" \
-            >/dev/null; then
-            printf "%s\n" \
-                "server {" \
-                "    server_name \"$FQDN\";" \
-                "    listen 443 ssl;" \
-                "    listen [::]:443 ssl;" \
-                "    http2 on;" \
-                "    ssl_certificate \"/etc/nginx/ssl/$FQDN.crt\";" \
-                "    ssl_certificate_key \"/etc/nginx/ssl/$FQDN.key\";" \
-                "    include sites/$FILENAME.d/*.conf;" \
-                "}" \
-                | sudo tee -a "/etc/nginx/sites/$FILENAME.conf" \
-                    >/dev/null
-        fi
-        ;;
-    *)
-        if exists apt-get; then
-            sudo apt-get install -yq software-properties-common
-            sudo add-apt-repository universe
-            sudo apt-get update
-            sudo apt-get install -yq certbot python3-certbot-nginx
-        elif exists pacman; then
-            sudo pacman -qS --needed --noconfirm certbot-nginx
-        fi
-        if sudo test ! -d "/etc/letsencrypt/live/$FQDN"; then
-            sudo certbot certonly -n --nginx --agree-tos --no-eff-email \
-                -m "root@$FQDN" -d "$FQDN" --cert-name "$FQDN"
-        fi
-        sudo certbot install -n --nginx --reinstall -d "$FQDN" \
-            --cert-name "$FQDN"
-        <"/etc/nginx/sites/$FILENAME.conf" sed \
-            's/\(443\|'"${PORT:-443}"'\) ssl\( http2\|\);/'"$(
-            )${PORT:-443}"' ssl http2;/' \
-            | sponge "/etc/nginx/sites/$FILENAME.conf"
-        sudo systemctl enable --now certbot-renew.timer
-        ;;
-    esac
-    sudo systemctl reload nginx || sudo systemctl restart nginx || true
+	echo "$FQDN" | grep -qF . || die "ERROR: Invalid FQDN"
+	[ "${HTTPD:-nginx}" = nginx ] \
+		|| die "ERROR: SSL installation not implemented for $HTTPD"
+	case "$FQDN" in
+	*.ts.net)
+		sudo mkdir -p /etc/nginx/ssl/
+		sudo tailscale cert --cert-file "/etc/nginx/ssl/$FQDN.crt" \
+			--key-file "/etc/nginx/ssl/$FQDN.key" "$FQDN"
+		echo "tailscale"
+		if ! grep ssl_certificate "/etc/nginx/sites/$FILENAME.conf" \
+			>/dev/null; then
+			printf "%s\n" \
+				"server {" \
+				"    server_name \"$FQDN\";" \
+				"    listen 443 ssl;" \
+				"    listen [::]:443 ssl;" \
+				"    http2 on;" \
+				"    ssl_certificate \"/etc/nginx/ssl/$FQDN.crt\";" \
+				"    ssl_certificate_key \"/etc/nginx/ssl/$FQDN.key\";" \
+				"    include sites/$FILENAME.d/*.conf;" \
+				"}" \
+				| sudo tee -a "/etc/nginx/sites/$FILENAME.conf" \
+					>/dev/null
+		fi
+		;;
+	*)
+		if exists apt-get; then
+			sudo apt-get install -yq software-properties-common
+			sudo add-apt-repository universe
+			sudo apt-get update
+			sudo apt-get install -yq certbot python3-certbot-nginx
+		elif exists pacman; then
+			sudo pacman -qS --needed --noconfirm certbot-nginx
+		fi
+		if sudo test ! -d "/etc/letsencrypt/live/$FQDN"; then
+			sudo certbot certonly -n --nginx --agree-tos --no-eff-email \
+				-m "root@$FQDN" -d "$FQDN" --cert-name "$FQDN"
+		fi
+		sudo certbot install -n --nginx --reinstall -d "$FQDN" \
+			--cert-name "$FQDN"
+		<"/etc/nginx/sites/$FILENAME.conf" sed \
+			's/\(443\|'"${PORT:-443}"'\) ssl\( http2\|\);/'"$(
+			)${PORT:-443}"' ssl http2;/' \
+			| sponge "/etc/nginx/sites/$FILENAME.conf"
+		sudo systemctl enable --now certbot-renew.timer
+		;;
+	esac
+	sudo systemctl reload nginx || sudo systemctl restart nginx || true
 fi
diff --git a/XDG_BIN_HOME/flacrename b/XDG_BIN_HOME/flacrename
--- a/XDG_BIN_HOME/flacrename
+++ b/XDG_BIN_HOME/flacrename
@@ -3,57 +3,57 @@
 set -eu
 
 gettags() { #@: files to get tags from
-    for x; do
-        case "$x" in
-        *.flac) metaflac --export-tags-to=- "$x" | sed 's/[^=]*/\U&/' ;;
-        *.mp3)
-            mid3v2 -l "$x" | awk -vFS== '
-                /^[0-9A-Z][0-9A-Z][0-9A-Z][0-9A-Z]=/ {
-                    tags[$1] = $2
-                }
-                END {
-                    map["TPE1"] = "ALBUMARTIST"
-                    map["TPE2"] = "ARTIST"
-                    map["TALB"] = "ALBUM"
-                    map["TYER"] = "DATE"
-                    map["TDRC"] = "DATE"
-                    map["TCON"] = "GENRE"
-                    map["TRCK"] = "TRACKNUMBER"
-                    map["TIT2"] = "TITLE"
-                    for (key in tags)
-                        if (key in map)
-                            printf("%s=%s\n", map[key], tags[key])
-                    if (! ("TPE2" in tags))
-                        printf("ARTIST=%s\n", tags["TPE1"])
-                }
-            '
-            ;;
-        esac
-    done
+	for x; do
+		case "$x" in
+		*.flac) metaflac --export-tags-to=- "$x" | sed 's/[^=]*/\U&/' ;;
+		*.mp3)
+			mid3v2 -l "$x" | awk -vFS== '
+				/^[0-9A-Z][0-9A-Z][0-9A-Z][0-9A-Z]=/ {
+					tags[$1] = $2
+				}
+				END {
+					map["TPE1"] = "ALBUMARTIST"
+					map["TPE2"] = "ARTIST"
+					map["TALB"] = "ALBUM"
+					map["TYER"] = "DATE"
+					map["TDRC"] = "DATE"
+					map["TCON"] = "GENRE"
+					map["TRCK"] = "TRACKNUMBER"
+					map["TIT2"] = "TITLE"
+					for (key in tags)
+						if (key in map)
+							printf("%s=%s\n", map[key], tags[key])
+					if (! ("TPE2" in tags))
+						printf("ARTIST=%s\n", tags["TPE1"])
+				}
+			'
+			;;
+		esac
+	done
 }
 
 getmeta() { #$1: metadata to get; $metadata: file to read from
-    <"$metadata" grep -q "^$1=" || return 1
-    sed -n 's/\//-/g; s/^'"$1"'=\(.*\)/\1/p' <"$metadata"
+	<"$metadata" grep -q "^$1=" || return 1
+	sed -n 's/\//-/g; s/^'"$1"'=\(.*\)/\1/p' <"$metadata"
 }
 
 tracknumber() { #$metadata: file to read from
-    track="$(getmeta TRACKNUMBER | sed 's/^0*//')"
-    disc="$(getmeta DISCNUMBER | sed 's/^0*//')"
-    [ -n "$disc" ] && printf '%02d.' "$disc"
-    printf '%02d' "$track"
+	track="$(getmeta TRACKNUMBER | sed 's/^0*//')"
+	disc="$(getmeta DISCNUMBER | sed 's/^0*//')"
+	[ -n "$disc" ] && printf '%02d.' "$disc"
+	printf '%02d' "$track"
 }
 
 trymove() { #$1: original location; $2: destination
-    [ "$1" = "$2" ] && return 0 || true
-    [ -f "$1" ] && [ -n "$2" ] && [ ! -e "$2" ] || return
-    mkdir -p "$(dirname "$2")"
-    mv "$1" "$2"
+	[ "$1" = "$2" ] && return 0 || true
+	[ -f "$1" ] && [ -n "$2" ] && [ ! -e "$2" ] || return
+	mkdir -p "$(dirname "$2")"
+	mv "$1" "$2"
 }
 
 trymovemeta() { #$1: location of media file; $2: ext regex; $3: destname
-    set -- "$(find "$(dirname "$1")" -name '*.'"$2" -print -quit)" "$2" "$3"
-    trymove "$1" "$3" || true
+	set -- "$(find "$(dirname "$1")" -name '*.'"$2" -print -quit)" "$2" "$3"
+	trymove "$1" "$3" || true
 }
 
 [ "$#" -ne 1 ] || ! [ -d "$1" ] || set -- "$1"/*.flac
@@ -63,25 +63,25 @@ LIB_ROOT="${XDG_MUSIC_DIR:=$(xdg-user-dir MUSIC)}"
 metadata="$(mktemp)"
 
 for i in "$@"; do
-    gettags "$i" >"$metadata" || continue
-    ext="${i##*.}"
-    dir="${LIB_ROOT}/$(getmeta ALBUMARTIST || getmeta ARTIST)/$(getmeta ALBUM)"
-    file="$(tracknumber) $(getmeta TITLE).$ext"
+	gettags "$i" >"$metadata" || continue
+	ext="${i##*.}"
+	dir="${LIB_ROOT}/$(getmeta ALBUMARTIST || getmeta ARTIST)/$(getmeta ALBUM)"
+	file="$(tracknumber) $(getmeta TITLE).$ext"
 
-    #Move relevant files
-    trymove "$i" "$dir/$file"
-    trymovemeta "$i" '[Cc][Uu][Ee]' "$dir/folder.cue"
-    trymovemeta "$i" '[Ll][Oo][Gg]' "$dir/folder.log"
-    trymove "$(dirname "$i")/folder.jpg" "$dir/folder.jpg" || true
-    trymovemeta "$i" '[Jj][Pp]*[Gg]' "$dir/folder.jpg"
+	#Move relevant files
+	trymove "$i" "$dir/$file"
+	trymovemeta "$i" '[Cc][Uu][Ee]' "$dir/folder.cue"
+	trymovemeta "$i" '[Ll][Oo][Gg]' "$dir/folder.log"
+	trymove "$(dirname "$i")/folder.jpg" "$dir/folder.jpg" || true
+	trymovemeta "$i" '[Jj][Pp]*[Gg]' "$dir/folder.jpg"
 
-    #Clean up
-    find "$(dirname "$i")" \( \
-        -name '*.auCDtect' -o -name '*.sfv' -o -name '*.nfo' -o \
-        -name '*.accurip' -o -name '*.m3u' -o -name '*.m3u8' -o \
-        -name '*.txt' -o -name '*.pdf' -o -name '*.log' -o \
-        -name '*.jpg' -o -name '*.cue' -o -name '*.CUE' \
-        \) -delete
-    find "$(dirname "$i")" -type d -exec rmdir -p {} \+ 2>/dev/null || true
-    rm "$metadata"
+	#Clean up
+	find "$(dirname "$i")" \( \
+		-name '*.auCDtect' -o -name '*.sfv' -o -name '*.nfo' -o \
+		-name '*.accurip' -o -name '*.m3u' -o -name '*.m3u8' -o \
+		-name '*.txt' -o -name '*.pdf' -o -name '*.log' -o \
+		-name '*.jpg' -o -name '*.cue' -o -name '*.CUE' \
+		\) -delete
+	find "$(dirname "$i")" -type d -exec rmdir -p {} \+ 2>/dev/null || true
+	rm "$metadata"
 done
diff --git a/XDG_BIN_HOME/mvln b/XDG_BIN_HOME/mvln
--- a/XDG_BIN_HOME/mvln
+++ b/XDG_BIN_HOME/mvln
@@ -5,12 +5,12 @@ set -eu
 [ "$#" -eq 2 ] || { echo "Usage: $(basename "$0") FILE TARGET" && exit 1; }
 
 if [ -d "$2" ]; then
-    mv "$1" "$2"
-    ln "$(readlink -f "$2")/$(basename "$1")" "$1"
+	mv "$1" "$2"
+	ln "$(readlink -f "$2")/$(basename "$1")" "$1"
 elif [ -f "$2" ]; then
-    echo "Error: $2 exists" >&2
-    exit 1
+	echo "Error: $2 exists" >&2
+	exit 1
 else
-    mv "$1" "$(readlink -f "$2")"
-    ln "$(readlink -f "$2")" "$1"
+	mv "$1" "$(readlink -f "$2")"
+	ln "$(readlink -f "$2")" "$1"
 fi
diff --git a/XDG_BIN_HOME/usb_img b/XDG_BIN_HOME/usb_img
--- a/XDG_BIN_HOME/usb_img
+++ b/XDG_BIN_HOME/usb_img
@@ -6,158 +6,158 @@ exists() { command -v "$1" >/dev/null 2>&1; }
 die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 device_of() { df -P "$1" | awk 'END { print $1 }'; }
 to_argv() (
-    set +x
-    while read -r LINE; do set -- "$@" "$LINE"; done
-    "$@"
+	set +x
+	while read -r LINE; do set -- "$@" "$LINE"; done
+	"$@"
 )
 
 clean() {
-    sync
-    sudo umount "$(device_of "$ROOT/boot")" "$(device_of "$ROOT")"
-    sudo rmdir "$ROOT" 2>/dev/null
-    ! losetup --list | grep -q "$DEVICE" || sudo losetup -d "$DEVICE"
+	sync
+	sudo umount "$(device_of "$ROOT/boot")" "$(device_of "$ROOT")"
+	sudo rmdir "$ROOT" 2>/dev/null
+	! losetup --list | grep -q "$DEVICE" || sudo losetup -d "$DEVICE"
 }
 
 download() { #1: url, 2: path
-    mkdir -p "$(dirname "$2")"
-    if exists curl; then
-        if [ -e "$2" ]; then
-            curl -fLo "$2" -z "$2" "$1"
-        else
-            curl -fLo "$2" "$1"
-        fi
-    elif exists wget; then
-        wget "$1" -O "$2"
-    fi
+	mkdir -p "$(dirname "$2")"
+	if exists curl; then
+		if [ -e "$2" ]; then
+			curl -fLo "$2" -z "$2" "$1"
+		else
+			curl -fLo "$2" "$1"
+		fi
+	elif exists wget; then
+		wget "$1" -O "$2"
+	fi
 }
 
 get_target_arch() {
-    case "$1" in
-    rpi1) echo armv6 ;;
-    rpi2) echo armv7 ;;
-    rpi3) echo aarch64 ;;
-    rpi4) echo aarch64 ;;
-    rpi5) echo aarch64 ;;
-    usb) echo x86_64 ;;
-    xps13) echo x86_64 ;;
-    esac
+	case "$1" in
+	rpi1) echo armv6 ;;
+	rpi2) echo armv7 ;;
+	rpi3) echo aarch64 ;;
+	rpi4) echo aarch64 ;;
+	rpi5) echo aarch64 ;;
+	usb) echo x86_64 ;;
+	xps13) echo x86_64 ;;
+	esac
 }
 
 get_rpi_image() { #1: version
-    set -- "$(get_target_arch "$1" | sed 's/armv6//')"
-    set -- "rpi${1:+-$1}"
-    set -- "http://os.archlinuxarm.org/os/ArchLinuxARM-${1}-latest.tar.gz"
-    set -- "$1" "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/${1##*/}"
-    download "$@"
-    echo "$2"
+	set -- "$(get_target_arch "$1" | sed 's/armv6//')"
+	set -- "rpi${1:+-$1}"
+	set -- "http://os.archlinuxarm.org/os/ArchLinuxARM-${1}-latest.tar.gz"
+	set -- "$1" "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/${1##*/}"
+	download "$@"
+	echo "$2"
 }
 
 get_dev_for() { #1: path
-    mount | sed -n 's_\(/dev/[^ ]*\) on '"$1"' .*_\1_p'
+	mount | sed -n 's_\(/dev/[^ ]*\) on '"$1"' .*_\1_p'
 }
 
 create_root() {
-    exists mkfs.vfat || die "error: install mkfs.vfat"
-    exists mkfs.ext4 || die "error: install mkfs.ext4"
+	exists mkfs.vfat || die "error: install mkfs.vfat"
+	exists mkfs.ext4 || die "error: install mkfs.ext4"
 
-    sudo wipefs -a "$1"
-    if [ "${TARGET%[1-4]}" = rpi ]; then
-        echo 'o; n;p;1;;+500M; t;c; n;p;2;;; w;q;' \
-            | tr -d \  | tr ';' '\n' \
-            | sudo fdisk "$1" || true #Maybe rereading partition table failed
-    else
-        sudo sgdisk -zo "$1"
-        sudo sgdisk -n 1:0:200M -t 1:ef00 -A 2:set:2 "$1"
-        if [ "$TARGET" = xps13 ]; then
-            sudo sgdisk -n 2:+0:-16G -t 2:8304 "$1"
-            sudo sgdisk -N 3 -t 3:8200 "$1"
-        else
-            sudo sgdisk -N 2 -t 2:8304 "$1"
-        fi
-    fi
-    sync
-    sudo blockdev --rereadpt -v "$1" || sudo partprobe "$1"
-    (
-        set -- $(lsblk -lnoNAME "$1" | sort | sed '1d;s|^|/dev/|')
-        yes | sudo mkfs.ext4 $2 && sudo mount $2 "$ROOT"
-        cd "$ROOT"
-        yes | sudo mkfs.vfat $1 && sudo mkdir -p boot && sudo mount $1 boot
-        [ -z "${3:-}" ] || { sudo mkswap -L hibernate "$3"; }
-    )
-    [ -d "$ROOT" ] && [ -d "$ROOT/boot" ] || die "error: fs setup/mount failed"
+	sudo wipefs -a "$1"
+	if [ "${TARGET%[1-4]}" = rpi ]; then
+		echo 'o; n;p;1;;+500M; t;c; n;p;2;;; w;q;' \
+			| tr -d \  | tr ';' '\n' \
+			| sudo fdisk "$1" || true #Maybe rereading partition table failed
+	else
+		sudo sgdisk -zo "$1"
+		sudo sgdisk -n 1:0:200M -t 1:ef00 -A 2:set:2 "$1"
+		if [ "$TARGET" = xps13 ]; then
+			sudo sgdisk -n 2:+0:-16G -t 2:8304 "$1"
+			sudo sgdisk -N 3 -t 3:8200 "$1"
+		else
+			sudo sgdisk -N 2 -t 2:8304 "$1"
+		fi
+	fi
+	sync
+	sudo blockdev --rereadpt -v "$1" || sudo partprobe "$1"
+	(
+		set -- $(lsblk -lnoNAME "$1" | sort | sed '1d;s|^|/dev/|')
+		yes | sudo mkfs.ext4 $2 && sudo mount $2 "$ROOT"
+		cd "$ROOT"
+		yes | sudo mkfs.vfat $1 && sudo mkdir -p boot && sudo mount $1 boot
+		[ -z "${3:-}" ] || { sudo mkswap -L hibernate "$3"; }
+	)
+	[ -d "$ROOT" ] && [ -d "$ROOT/boot" ] || die "error: fs setup/mount failed"
 }
 
 usb_img() { #1: path #2: target
-    [ $# -ge 2 ] \
-        || die "usage: usb_img DEVPATH TARGET [SIZE (only if loop device)]"
-    ROOT="$(mktemp -d)"
-    DEVICE="$1"
-    trap clean EXIT
-    TARGET="$2"
-    if [ $# -eq 3 ] && [ ! -b "$1" ]; then
-        sudo modprobe loop
-        truncate -s "$3" "$1"
-        set -- "$(sudo losetup -fP --show "$1")" "$2"
-        expr "$1" : /dev/ || die "error: loopback setup failed"
-    fi
-    create_root "$1"
-    if [ "${TARGET%[1-5]}" = rpi ]; then
-        echo "Actually downloading/writing data. This may take a while..." >&2
-        sudo bsdtar -xpf "$(get_rpi_image "$2")" -C "$ROOT"
-        [ "$2" != rpi4 ] || sudo sed -i 's/mmcblk0/mmcblk1/g' "$ROOT/etc/fstab"
-        if [ "$2" = rpi5 ]; then
-            download http://mirror.archlinuxarm.org/aarch64/core/$(
-            )linux-rpi-6.6.28-1-aarch64.pkg.tar.xz \
-                "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/linux-rpi.pkg.tar.xz"
-            sudo rm -rf "$ROOT/boot"/*
-            sudo bsdtar -xpf \
-                "${XDG_CACHE_HOME:-$HOME/.cache}/$(
-                )rpi_img/linux-rpi.pkg.tar.xz" \
-                -C "$ROOT"
-            <"$ROOT/boot/cmdline.txt" sed \
-                "s|root=[^ ]*|root=$(get_dev_for "$ROOT")|" \
-                | sudo tee "$ROOT/boot/cmdline.txt.new" >/dev/null \
-                && sudo mv "$ROOT/boot/cmdline.txt.new" \
-                    "$ROOT/boot/cmdline.txt"
-            <"$ROOT/etc/fstab" sed \
-                -e "s|/dev/mmcblk0p2|$(get_dev_for "$ROOT")|" \
-                -e "s|/dev/mmcblk0p1|$(get_dev_for "$ROOT/boot")|" \
-                | sudo tee "$ROOT/etc/fstab.new" >/dev/null \
-                && sudo mv "$ROOT/etc/fstab.new" "$ROOT/etc/fstab"
-        fi
-    else
-        if [ "$TARGET" = usb ]; then
-            sudo pacman --needed --noconfirm -S archiso
-            </usr/share/archiso/configs/releng/packages.x86_64 grep \
-                -vE '^(#|grml-zsh-config)' \
-                | to_argv sudo pacstrap "$ROOT"
-        else
-            sudo pacstrap "$ROOT" base linux linux-firmware \
-                arch-install-scripts
-        fi
-    fi
-    if [ "$(get_target_arch "$2")" = "$(uname -m)" ]; then
-        sudo cp -rL --preserve=mode \
-            "${DOTFILES-$PREFIX/dot}/PREFIX/src/roles" "$ROOT/usr/local/src"
-        sudo arch-chroot "$ROOT" sh -euc '
-            cd /usr/local/src/roles;
-            export CHROOT=true;
-            export HOSTNAME='"$HOSTNAME"';
-            export TARGET='"$TARGET"';
-            ./install_arch
-            ./init
-            printf "1234\\n1234\\n" | passwd
-            usermod -aG video mil
-        '
-        sudo git clone "${DOTFILES-$PREFIX/dot}/.git" \
-            "$ROOT/home/mil/.local/dot"
-        sudo git -C "$ROOT/home/mil/.local/dot" \
-            remote set-url origin https://milhnl@github.com/milhnl/dotfiles
-        sudo arch-chroot "$ROOT" sudo -u mil sh -euc '
-            sudo chown -R mil:mil "$HOME/.local"
-            . /usr/local/src/roles/home
-        '
-    fi
+	[ $# -ge 2 ] \
+		|| die "usage: usb_img DEVPATH TARGET [SIZE (only if loop device)]"
+	ROOT="$(mktemp -d)"
+	DEVICE="$1"
+	trap clean EXIT
+	TARGET="$2"
+	if [ $# -eq 3 ] && [ ! -b "$1" ]; then
+		sudo modprobe loop
+		truncate -s "$3" "$1"
+		set -- "$(sudo losetup -fP --show "$1")" "$2"
+		expr "$1" : /dev/ || die "error: loopback setup failed"
+	fi
+	create_root "$1"
+	if [ "${TARGET%[1-5]}" = rpi ]; then
+		echo "Actually downloading/writing data. This may take a while..." >&2
+		sudo bsdtar -xpf "$(get_rpi_image "$2")" -C "$ROOT"
+		[ "$2" != rpi4 ] || sudo sed -i 's/mmcblk0/mmcblk1/g' "$ROOT/etc/fstab"
+		if [ "$2" = rpi5 ]; then
+			download http://mirror.archlinuxarm.org/aarch64/core/$(
+			)linux-rpi-6.6.28-1-aarch64.pkg.tar.xz \
+				"${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/linux-rpi.pkg.tar.xz"
+			sudo rm -rf "$ROOT/boot"/*
+			sudo bsdtar -xpf \
+				"${XDG_CACHE_HOME:-$HOME/.cache}/$(
+				)rpi_img/linux-rpi.pkg.tar.xz" \
+				-C "$ROOT"
+			<"$ROOT/boot/cmdline.txt" sed \
+				"s|root=[^ ]*|root=$(get_dev_for "$ROOT")|" \
+				| sudo tee "$ROOT/boot/cmdline.txt.new" >/dev/null \
+				&& sudo mv "$ROOT/boot/cmdline.txt.new" \
+					"$ROOT/boot/cmdline.txt"
+			<"$ROOT/etc/fstab" sed \
+				-e "s|/dev/mmcblk0p2|$(get_dev_for "$ROOT")|" \
+				-e "s|/dev/mmcblk0p1|$(get_dev_for "$ROOT/boot")|" \
+				| sudo tee "$ROOT/etc/fstab.new" >/dev/null \
+				&& sudo mv "$ROOT/etc/fstab.new" "$ROOT/etc/fstab"
+		fi
+	else
+		if [ "$TARGET" = usb ]; then
+			sudo pacman --needed --noconfirm -S archiso
+			</usr/share/archiso/configs/releng/packages.x86_64 grep \
+				-vE '^(#|grml-zsh-config)' \
+				| to_argv sudo pacstrap "$ROOT"
+		else
+			sudo pacstrap "$ROOT" base linux linux-firmware \
+				arch-install-scripts
+		fi
+	fi
+	if [ "$(get_target_arch "$2")" = "$(uname -m)" ]; then
+		sudo cp -rL --preserve=mode \
+			"${DOTFILES-$PREFIX/dot}/PREFIX/src/roles" "$ROOT/usr/local/src"
+		sudo arch-chroot "$ROOT" sh -euc '
+			cd /usr/local/src/roles;
+			export CHROOT=true;
+			export HOSTNAME='"$HOSTNAME"';
+			export TARGET='"$TARGET"';
+			./install_arch
+			./init
+			printf "1234\\n1234\\n" | passwd
+			usermod -aG video mil
+		'
+		sudo git clone "${DOTFILES-$PREFIX/dot}/.git" \
+			"$ROOT/home/mil/.local/dot"
+		sudo git -C "$ROOT/home/mil/.local/dot" \
+			remote set-url origin https://milhnl@github.com/milhnl/dotfiles
+		sudo arch-chroot "$ROOT" sudo -u mil sh -euc '
+			sudo chown -R mil:mil "$HOME/.local"
+			. /usr/local/src/roles/home
+		'
+	fi
 }
 
 usb_img "$@"
diff --git a/XDG_BIN_HOME/winvm b/XDG_BIN_HOME/winvm
--- a/XDG_BIN_HOME/winvm
+++ b/XDG_BIN_HOME/winvm
@@ -9,178 +9,178 @@ in_dir() (cd "$1" && shift && "$@")
 escape() { echo "$1" | sed s/\'/\'\\\'\'/g; }
 
 get_unused_id() (
-    cd "$XDG_DATA_HOME/winvm" || { echo 0 && return; }
-    set -- 0 $(seq $(($(cat */id 2>/dev/null | sort | tail -n1) + 1)))
-    for i; do
-        if ! cat */id 2>/dev/null | grep -q "^$i$"; then
-            echo "$i"
-            return
-        fi
-    done
+	cd "$XDG_DATA_HOME/winvm" || { echo 0 && return; }
+	set -- 0 $(seq $(($(cat */id 2>/dev/null | sort | tail -n1) + 1)))
+	for i; do
+		if ! cat */id 2>/dev/null | grep -q "^$i$"; then
+			echo "$i"
+			return
+		fi
+	done
 )
 
 get_vm_id() { #1:vm 2?:host
-    if [ "$#" -eq 1 ] || [ -z "${2:-}" ]; then
-        cat "$XDG_DATA_HOME/winvm/$1/id" || return 1
-    else
-        ssh "$2" cat '"${XDG_DATA_HOME:-$HOME/.local/share}/winvm/'"$1"'/id"' \
-            || return 1
-    fi
+	if [ "$#" -eq 1 ] || [ -z "${2:-}" ]; then
+		cat "$XDG_DATA_HOME/winvm/$1/id" || return 1
+	else
+		ssh "$2" cat '"${XDG_DATA_HOME:-$HOME/.local/share}/winvm/'"$1"'/id"' \
+			|| return 1
+	fi
 }
 
 get_port() { #1:id 2:port
-    echo $((10000 + 1000 * $1 + $2))
+	echo $((10000 + 1000 * $1 + $2))
 }
 
 ssh_judo() {
-    OPTIND=1
-    unset script sshop envvar
-    while getopts 's:o:e:' OPT "$@"; do
-        case "$OPT" in
-        s) script="$OPTARG" ;;
-        o) sshop="${sshop+$sshop }'$(escape "-o$OPTARG")'" ;;
-        e) envvar="${envvar+$envvar }'$(escape "$OPTARG")'" ;;
-        esac
-    done
-    shift $(($OPTIND - 1))
-    eval "set -- ${sshop-} \"\$@\""
-    tar -chf/dev/stdout "$script"/* \
-        | ssh "$@" \
-            "tar -xf/dev/stdin; \
-                env ${envvar:-} sh \"$script/script\" </dev/null; \
-                rm -r \"$script\""
+	OPTIND=1
+	unset script sshop envvar
+	while getopts 's:o:e:' OPT "$@"; do
+		case "$OPT" in
+		s) script="$OPTARG" ;;
+		o) sshop="${sshop+$sshop }'$(escape "-o$OPTARG")'" ;;
+		e) envvar="${envvar+$envvar }'$(escape "$OPTARG")'" ;;
+		esac
+	done
+	shift $(($OPTIND - 1))
+	eval "set -- ${sshop-} \"\$@\""
+	tar -chf/dev/stdout "$script"/* \
+		| ssh "$@" \
+			"tar -xf/dev/stdin; \
+				env ${envvar:-} sh \"$script/script\" </dev/null; \
+				rm -r \"$script\""
 }
 
 install_deps() {
-    sudo pacman -q --noconfirm -S --needed base-devel vagrant virtualbox \
-        dnsmasq net-tools virtualbox-host-modules-arch linux-headers
-    sudo modprobe vboxdrv
-    mkdir -p "$XDG_DATA_HOME/vboxvms"
-    vboxmanage setproperty machinefolder "$XDG_DATA_HOME/vboxvms/"
+	sudo pacman -q --noconfirm -S --needed base-devel vagrant virtualbox \
+		dnsmasq net-tools virtualbox-host-modules-arch linux-headers
+	sudo modprobe vboxdrv
+	mkdir -p "$XDG_DATA_HOME/vboxvms"
+	vboxmanage setproperty machinefolder "$XDG_DATA_HOME/vboxvms/"
 }
 
 create_config() { #1:name 2:id
-    HOST_RDP_PORT="$(get_port "$2" 389)"
-    HOST_SSH_PORT="$(get_port "$2" 22)"
-    HOST_WSSH_PORT="$(get_port "$2" 23)"
+	HOST_RDP_PORT="$(get_port "$2" 389)"
+	HOST_SSH_PORT="$(get_port "$2" 22)"
+	HOST_WSSH_PORT="$(get_port "$2" 23)"
 
-    mkdir -p "$XDG_DATA_HOME/winvm/$1"
-    echo "$2" >"$XDG_DATA_HOME/winvm/$1/id"
-    cp "$XDG_CONFIG_HOME/winvm/Vagrantfile" \
-        "$XDG_DATA_HOME/winvm/$1/Vagrantfile"
-    cp "$XDG_CONFIG_HOME/winvm"/*.ps1 \
-        "$XDG_DATA_HOME/winvm/$1/"
-    <"$XDG_CONFIG_HOME/winvm/ssh_config" sed \
-        -e "s|\\\$VM_NAME|$1|" \
-        -e "s|\\\$HOST_WSSH_PORT|$HOST_WSSH_PORT|" \
-        -e "s|\\\$HOST_SSH_PORT|$HOST_SSH_PORT|" \
-        -e "s|\\\$XDG_DATA_HOME|$XDG_DATA_HOME|" \
-        >"$XDG_DATA_HOME/winvm/$1/ssh_config"
-    printf "username:s:%s\r\nfull address:s:localhost:%s\r\n" \
-        "WINVM\\vagrant" "$HOST_RDP_PORT" \
-        >"$XDG_DATA_HOME/winvm/$1/macOS.rdp"
+	mkdir -p "$XDG_DATA_HOME/winvm/$1"
+	echo "$2" >"$XDG_DATA_HOME/winvm/$1/id"
+	cp "$XDG_CONFIG_HOME/winvm/Vagrantfile" \
+		"$XDG_DATA_HOME/winvm/$1/Vagrantfile"
+	cp "$XDG_CONFIG_HOME/winvm"/*.ps1 \
+		"$XDG_DATA_HOME/winvm/$1/"
+	<"$XDG_CONFIG_HOME/winvm/ssh_config" sed \
+		-e "s|\\\$VM_NAME|$1|" \
+		-e "s|\\\$HOST_WSSH_PORT|$HOST_WSSH_PORT|" \
+		-e "s|\\\$HOST_SSH_PORT|$HOST_SSH_PORT|" \
+		-e "s|\\\$XDG_DATA_HOME|$XDG_DATA_HOME|" \
+		>"$XDG_DATA_HOME/winvm/$1/ssh_config"
+	printf "username:s:%s\r\nfull address:s:localhost:%s\r\n" \
+		"WINVM\\vagrant" "$HOST_RDP_PORT" \
+		>"$XDG_DATA_HOME/winvm/$1/macOS.rdp"
 
-    mkdir -p "$HOME/.ssh/conf.d"
-    printf "Include %s/winvm/*/ssh_config" "$XDG_DATA_HOME" \
-        >"$HOME/.ssh/conf.d/winvm"
+	mkdir -p "$HOME/.ssh/conf.d"
+	printf "Include %s/winvm/*/ssh_config" "$XDG_DATA_HOME" \
+		>"$HOME/.ssh/conf.d/winvm"
 }
 
 vagrant_for_vm() { #1:id 2...:vagrantargs
-    export VAGRANT_DEFAULT_PROVIDER=virtualbox
-    export VAGRANT_CWD="$XDG_DATA_HOME/winvm/$VM_NAME"
-    export HOST_RDP_PORT="$(get_port "$1" 389)"
-    export HOST_SSH_PORT="$(get_port "$1" 22)"
-    export HOST_WSSH_PORT="$(get_port "$1" 23)"
-    export PUBKEY="$(ssh-add -L | head -n 1)"
-    shift
-    vagrant "$@"
+	export VAGRANT_DEFAULT_PROVIDER=virtualbox
+	export VAGRANT_CWD="$XDG_DATA_HOME/winvm/$VM_NAME"
+	export HOST_RDP_PORT="$(get_port "$1" 389)"
+	export HOST_SSH_PORT="$(get_port "$1" 22)"
+	export HOST_WSSH_PORT="$(get_port "$1" 23)"
+	export PUBKEY="$(ssh-add -L | head -n 1)"
+	shift
+	vagrant "$@"
 }
 
 winvm() {
-    export VM_NAME=winvm
-    while getopts 'h:v:' OPT "$@"; do
-        case "$OPT" in
-        h) HOST_NAME="$OPTARG" ;;
-        v) VM_NAME="$OPTARG" ;;
-        esac
-    done
-    shift "$(($OPTIND - 1))"
+	export VM_NAME=winvm
+	while getopts 'h:v:' OPT "$@"; do
+		case "$OPT" in
+		h) HOST_NAME="$OPTARG" ;;
+		v) VM_NAME="$OPTARG" ;;
+		esac
+	done
+	shift "$(($OPTIND - 1))"
 
-    if [ "$1" = global-status ]; then
-        vagrant global-status \
-            | sed '1d;/^--*$/d;/^ $/,$d;s/  */\t/g' \
-            | while read -r LINE; do
-                printf '%s\t%s\n' \
-                    "$(cat "$(echo "$LINE" | cut -f5)/id")" "$LINE"
-            done \
-            | sed "s|$XDG_DATA_HOME|\\\$XDG_DATA_HOME|" \
-            | cut -f1,2,3,5,6 \
-            | sort
-        exit $?
-    elif [ "$1" = provision ]; then
-        install_deps
-        id="$(get_unused_id)"
-        create_config "$VM_NAME" "$id"
+	if [ "$1" = global-status ]; then
+		vagrant global-status \
+			| sed '1d;/^--*$/d;/^ $/,$d;s/  */\t/g' \
+			| while read -r LINE; do
+				printf '%s\t%s\n' \
+					"$(cat "$(echo "$LINE" | cut -f5)/id")" "$LINE"
+			done \
+			| sed "s|$XDG_DATA_HOME|\\\$XDG_DATA_HOME|" \
+			| cut -f1,2,3,5,6 \
+			| sort
+		exit $?
+	elif [ "$1" = provision ]; then
+		install_deps
+		id="$(get_unused_id)"
+		create_config "$VM_NAME" "$id"
 
-        vagrant_for_vm "$id" up --provision
-        vagrant_for_vm "$id" halt
-        vagrant_for_vm "$id" up --provision
-        {
-            in_dir "${DOTFILES-$PREFIX/dot}" cat PREFIX/src/roles/init
-            echo "sudo -u mil mkdir -p ~mil/.local/dot"
-        } | ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" \
-            'wsl.exe -u root -- sh -'
-        in_dir "${DOTFILES-$PREFIX/dot}" tar -cf/dev/stdout . \
-            | ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" \
-                'wsl.exe -u mil --cd /home/mil/.local/dot -- tar -xf-'
-        ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" \
-            'wsl.exe -u mil -- sh ~/.local/dot/PREFIX/src/roles/home'
-        exit $?
-    else
-        create_config "$VM_NAME" "$(get_vm_id "$VM_NAME" "${HOST_NAME:-}")"
-        [ -z "${HOST_NAME:-}" ] \
-            || <"$XDG_DATA_HOME/winvm/$VM_NAME/Vagrantfile" sed \
-                -n 's/.*forwarded_port.*host: \([0-9]*\).*/\1/p' \
-            | (
-                set -- "$HOST_NAME" -f
-                while read -r PORT; do
-                    set -- "$@" -NTL "$PORT:localhost:$PORT"
-                done
-                ssh "$@"
-            )
-    fi
-    if [ "$1" = ssh ]; then
-        shift
-        ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" "$@"
-    elif [ "$1" = wssh ]; then
-        shift
-        ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "${VM_NAME}_wsl" "$@"
-    elif [ "$1" = rdp ]; then
-        case "$(uname -s)" in
-        Darwin)
-            open -a "Microsoft Remote Desktop" \
-                "$XDG_DATA_HOME/winvm/$VM_NAME/macOS.rdp"
-            ;;
-        Linux)
-            if exists wlfreerdp; then
-                daemon wlfreerdp +sec-tls /cert-ignore /v:localhost /p:3389 \
-                    /u:vagrant /p:vagrant /dynamic-resolution -grab-keyboard
-            elif exists rdesktop; then
-                printf "yes\n" \
-                    | daemon rdesktop localhost -u vagrant -p vagrant -K \
-                        -T winvm -g 1920x1102 -r clipboard:PRIMARYCLIPBOARD
-            else
-                printf "error: no RDP client. Install rdesktop/freerdp" >&2
-                exit 1
-            fi
-            ;;
-        esac
-    elif vagrant list-commands | sed '1,3d;s/ .*//' | grep -qx "$1"; then
-        vagrant_for_vm "$(get_vm_id "$VM_NAME" "${HOST_NAME:-}")" "$@"
-        [ "$1" != destroy ] || rm -r "$XDG_DATA_HOME/winvm/$VM_NAME"
-    else
-        "$@"
-    fi
+		vagrant_for_vm "$id" up --provision
+		vagrant_for_vm "$id" halt
+		vagrant_for_vm "$id" up --provision
+		{
+			in_dir "${DOTFILES-$PREFIX/dot}" cat PREFIX/src/roles/init
+			echo "sudo -u mil mkdir -p ~mil/.local/dot"
+		} | ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" \
+			'wsl.exe -u root -- sh -'
+		in_dir "${DOTFILES-$PREFIX/dot}" tar -cf/dev/stdout . \
+			| ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" \
+				'wsl.exe -u mil --cd /home/mil/.local/dot -- tar -xf-'
+		ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" \
+			'wsl.exe -u mil -- sh ~/.local/dot/PREFIX/src/roles/home'
+		exit $?
+	else
+		create_config "$VM_NAME" "$(get_vm_id "$VM_NAME" "${HOST_NAME:-}")"
+		[ -z "${HOST_NAME:-}" ] \
+			|| <"$XDG_DATA_HOME/winvm/$VM_NAME/Vagrantfile" sed \
+				-n 's/.*forwarded_port.*host: \([0-9]*\).*/\1/p' \
+			| (
+				set -- "$HOST_NAME" -f
+				while read -r PORT; do
+					set -- "$@" -NTL "$PORT:localhost:$PORT"
+				done
+				ssh "$@"
+			)
+	fi
+	if [ "$1" = ssh ]; then
+		shift
+		ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "$VM_NAME" "$@"
+	elif [ "$1" = wssh ]; then
+		shift
+		ssh -F"$XDG_DATA_HOME/winvm/$VM_NAME/ssh_config" "${VM_NAME}_wsl" "$@"
+	elif [ "$1" = rdp ]; then
+		case "$(uname -s)" in
+		Darwin)
+			open -a "Microsoft Remote Desktop" \
+				"$XDG_DATA_HOME/winvm/$VM_NAME/macOS.rdp"
+			;;
+		Linux)
+			if exists wlfreerdp; then
+				daemon wlfreerdp +sec-tls /cert-ignore /v:localhost /p:3389 \
+					/u:vagrant /p:vagrant /dynamic-resolution -grab-keyboard
+			elif exists rdesktop; then
+				printf "yes\n" \
+					| daemon rdesktop localhost -u vagrant -p vagrant -K \
+						-T winvm -g 1920x1102 -r clipboard:PRIMARYCLIPBOARD
+			else
+				printf "error: no RDP client. Install rdesktop/freerdp" >&2
+				exit 1
+			fi
+			;;
+		esac
+	elif vagrant list-commands | sed '1,3d;s/ .*//' | grep -qx "$1"; then
+		vagrant_for_vm "$(get_vm_id "$VM_NAME" "${HOST_NAME:-}")" "$@"
+		[ "$1" != destroy ] || rm -r "$XDG_DATA_HOME/winvm/$VM_NAME"
+	else
+		"$@"
+	fi
 }
 
 winvm "$@"
