Add doas support to init role

diff --git a/PREFIX/src/roles/init b/PREFIX/src/roles/init
--- a/PREFIX/src/roles/init
+++ b/PREFIX/src/roles/init
@@ -8,7 +8,7 @@ getsh() { command -v zsh || command -v bash || command -v ash || echo sh; }
 lineinfile() {
 	sudo grep -qxF "$2" "$1" || echo "$2" | sudo tee -a "$1" >/dev/null
 }
-[ $(id -u) = 0 ] && ! exists sudo && sudo() { "$@"; } || true #just run as root
+[ $(id -u) -ne 0 ] || sudo() { "$@"; } #just run as root
 rndpasswd() {
 	{ LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 2>/dev/null || :; } \
 		| head -c64 \
@@ -144,18 +144,34 @@ else
 				sudo systemctl enable sshd
 			fi
 		elif exists apk; then
-			sudo apk -q add openssh sudo
+			if apk query doas-sudo-shim | grep -q .; then
+				sudo apk -q add openssh doas doas-sudo-shim
+			else
+				sudo apk -q add openssh doas
+				printf '#!/bin/sh\nexec doas "$@"\n' \
+					| sudo tee "/usr/bin/sudo" >/dev/null
+				sudo chmod +x "/usr/bin/sudo"
+			fi
 			sudo rc-service sshd restart
 		elif exists apt-get; then
 			sudo apt-get install -qy openssh-server sudo
 			sudo systemctl enable --now ssh
 			sudo systemctl reload ssh
 		fi
-		lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
-		unset -f sudo 2>/dev/null || :
-		exists sudo && ps -A 2>/dev/null | grep -q sshd \
+		if exists doas; then
+			lineinfile /etc/doas.conf 'permit nopass :wheel'
+			lineinfile /etc/doas.conf 'permit nopass keepenv root'
+		elif (
+			unset -f sudo 2>/dev/null || :
+			exists sudo
+		); then
+			lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
+		else
+			die "sudo setup failed"
+		fi
+		ps -A 2>/dev/null | grep -q '[s]shd' \
 			|| "${CHROOT:-false}" \
-			|| die "sudo/ssh setup failed"
+			|| die "ssh setup failed"
 		;;
 	esac
 fi
