Don't check running sshd in chrooted init role

diff --git a/PREFIX/src/roles/init b/PREFIX/src/roles/init
--- a/PREFIX/src/roles/init
+++ b/PREFIX/src/roles/init
@@ -126,7 +126,9 @@ else
         fi
         lineinfile /etc/sudoers '%wheel ALL=(ALL) NOPASSWD: ALL'
         unset -f sudo
-        exists sudo && ps -A | grep -q sshd || die "sudo/ssh setup failed"
+        exists sudo && ps -A 2>/dev/null | grep -q sshd \
+            || "${CHROOT:-false}" \
+            || die "sudo/ssh setup failed"
         ;;
     esac
 fi
