Fix invocation of getopts

diff --git a/PREFIX/src/roles/mqtt_broker b/PREFIX/src/roles/mqtt_broker
--- a/PREFIX/src/roles/mqtt_broker
+++ b/PREFIX/src/roles/mqtt_broker
@@ -10,9 +10,10 @@ set_file() ( #1:file 2:mod 3:own ...:lines
         o) own="$OPTARG" ;;
         g) grp="$OPTARG" ;;
         m) mod="$OPTARG" ;;
+        *) printf "ERROR: Unknown option: %s" "$OPT" >&2 && return 1 ;;
         esac
     done
-    shift $(($OPTIND - 1))
+    shift $((OPTIND - 1)) && OPTIND=1
     file="$1" && shift
     if ! [ -d "$(dirname "$file")" ]; then
         mkdir "$(dirname "$file")"
diff --git a/XDG_BIN_HOME/browser b/XDG_BIN_HOME/browser
--- a/XDG_BIN_HOME/browser
+++ b/XDG_BIN_HOME/browser
@@ -2,6 +2,7 @@
 #browser - open default browser on current platform
 set -eu
 
+die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 
 # FIREFOX ---------------------------------------------------------------------
@@ -97,7 +98,8 @@ while getopts 'b:P:' OPT "$@"; do
     case "$OPT" in
     b) BROWSER="$OPTARG" ;;
     P) PROFILE="$OPTARG" ;;
+    *) die "ERROR: Unknown option: %OPT" ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1)) && OPTIND=1
 "browser_$BROWSER" "$@"
diff --git a/XDG_BIN_HOME/gui b/XDG_BIN_HOME/gui
--- a/XDG_BIN_HOME/gui
+++ b/XDG_BIN_HOME/gui
@@ -1,6 +1,8 @@
 #!/usr/bin/env sh
 set -eu
 
+die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
+
 quote() {
     for x; do
         printf %s\\n "$x" \
@@ -21,10 +23,11 @@ ssh_or_sh() {
 while getopts "u:" OPT "$@"; do
     case "$OPT" in
     u) REMOTE_USER="$OPTARG" ;;
+    *) die "ERROR: Unknown option: %OPT" ;;
     esac
 done
 
-shift "$(($OPTIND - 1))"
+shift $((OPTIND - 1)) && OPTIND=1
 HOST="${1:-$REMOTE_HOST}"
 shift
 CMD="$(quote "$@" | sed "s/'/'\\\\''/g")"
diff --git a/XDG_BIN_HOME/notify-send b/XDG_BIN_HOME/notify-send
--- a/XDG_BIN_HOME/notify-send
+++ b/XDG_BIN_HOME/notify-send
@@ -35,9 +35,10 @@ notify_send_dbus() {
             rfile="$OPTARG"
             ! [ -f "$rfile" ] || <"$rfile" read rid || :
             ;;
+        *) die "ERROR: Unknown option: %OPT" ;;
         esac
     done
-    shift $(($OPTIND - 1))
+    shift $((OPTIND - 1)) && OPTIND=1
     gdbus call --session --object-path /org/freedesktop/Notifications \
         --dest org.freedesktop.Notifications \
         --method org.freedesktop.Notifications.Notify \
@@ -59,10 +60,13 @@ notify_send_macos() {
                 ;;
             esac
             ;;
-        h) hint="${hint:-}$(to_hint "$OPTARG"), " ;;
+        t | i | c | p | r | R)
+            printf "warning: macOS notify-send does not support -%s" "$OPT" >&2
+            ;;
+        *) die "ERROR: Unknown option: %OPT" ;;
         esac
     done
-    shift $(($OPTIND - 1))
+    shift $((OPTIND - 1)) && OPTIND=1
 
     export title="$([ -n "${2:-}" ] && echo "$1" \
         || echo "$(ps -o comm= $PPID)")"
diff --git a/XDG_BIN_HOME/rename b/XDG_BIN_HOME/rename
--- a/XDG_BIN_HOME/rename
+++ b/XDG_BIN_HOME/rename
@@ -1,6 +1,8 @@
 #!/usr/bin/env sh
 set -eu
 
+die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
+
 show() {
     printf "\033[0;31m%s \033[0;32m%s\033[0m\n" "$1" "$2"
 }
@@ -12,9 +14,10 @@ while getopts 'ce:E:' OPT "$@"; do
     c) mv=show ;;
     e) cmd="${cmd+$cmd | }$sed '$(echo "$OPTARG" | sed "s/'/'\\\\''/")'" ;; #"
     E) sed='sed -E' ;;
+    *) die "ERROR: Unknown option: %OPT" ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1)) && OPTIND=1
 for x; do
     y="$(echo "$x" | eval "$cmd")" || exit 1
     if [ "$x" != "$y" ]; then
diff --git a/XDG_BIN_HOME/winvm b/XDG_BIN_HOME/winvm
--- a/XDG_BIN_HOME/winvm
+++ b/XDG_BIN_HOME/winvm
@@ -2,6 +2,7 @@
 #winvm - manage windows vm
 set -eu
 
+die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 daemon() (exec "$@" >/dev/null 2>&1 &)
 in_dir() (cd "$1" && shift && "$@")
@@ -33,16 +34,16 @@ get_port() { #1:id 2:port
 }
 
 ssh_judo() {
-    OPTIND=1
     unset script sshop envvar
     while getopts 's:o:e:' OPT "$@"; do
         case "$OPT" in
         s) script="$OPTARG" ;;
         o) sshop="${sshop+$sshop }'$(escape "-o$OPTARG")'" ;;
         e) envvar="${envvar+$envvar }'$(escape "$OPTARG")'" ;;
+        *) die "ERROR: Unknown option: %OPT" ;;
         esac
     done
-    shift $(($OPTIND - 1))
+    shift $((OPTIND - 1)) && OPTIND=1
     eval "set -- ${sshop-} \"\$@\""
     tar -chf/dev/stdout "$script"/* \
         | ssh "$@" \
@@ -102,9 +103,10 @@ winvm() {
         case "$OPT" in
         h) HOST_NAME="$OPTARG" ;;
         v) VM_NAME="$OPTARG" ;;
+        *) die "ERROR: Unknown option: %OPT" ;;
         esac
     done
-    shift "$(($OPTIND - 1))"
+    shift $((OPTIND - 1)) && OPTIND=1
 
     if [ "$1" = global-status ]; then
         vagrant global-status \
