Alpine (WIP)

diff --git a/PREFIX/src/roles/networking b/PREFIX/src/roles/networking
--- a/PREFIX/src/roles/networking
+++ b/PREFIX/src/roles/networking
@@ -1,41 +1,45 @@
 #!/usr/bin/env sh
-#wifi_client - role to set up (wireless) networks
+#networking - role to set up (wireless) networks
 set -eu
 
 die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 
-export IFNAME="$(
-	find /sys/class/net -follow -maxdepth 2 -name phy80211 2>/dev/null \
-		| head \
-		| cut -d / -f 5
-)"
-
 if exists apk; then
-	sudo apk add -q iwd bonding dbus
+	#Add iwd-openrc here explicitly to fail hard on apk_repofetch bugs
+	sudo apk add -q iwd iwd-openrc bonding dbus \
+		|| sudo apk add -q wpa_supplicant bonding
 elif exists pacman; then
-	sudo pacman --needed --noconfirm -qS netctl-auto
+	sudo pacman --needed --noconfirm -qS netctl
 fi
 
-if exists iwctl; then
-	install() {
-		printf %s\\n \
-			'[Security]' \
-			"Passphrase=$P" \
-			'' \
-			'[Settings]' \
-			'AutoConnect=true' \
-			| sudo tee \
-				/var/lib/iwd/"$S.$([ "$T" = WPA ] && echo psk || echo open)" \
-				>/dev/null
-	}
+if exists ifupdown; then
+	if rc-service --exists iwd && rc-service --exists dbus; then
+		install() {
+			printf %s\\n \
+				'[Security]' \
+				"Passphrase=$P" \
+				'' \
+				'[Settings]' \
+				'AutoConnect=true' \
+				| sudo tee /var/lib/iwd/"$S.$(
+					[ "$T" = WPA ] && echo psk || echo open
+				)" >/dev/null
+		}
+	else
+		CCn="$(printf \\nx)" && CCn="${CCn%x}"
+		install() {
+			printf %s \
+				"network={$CCn" \
+				"    ssid=\"$S\"$CCn" \
+				"    psk=\"$P\"$CCn" \
+				"$([ ! "${H-}" = true ] || printf "    scan_ssid=1$CCn")" \
+				"}$CCn" \
+				| sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf \
+					>/dev/null
+		}
+	fi
 	commit() {
-		sudo grep "auto $IFNAME" /etc/network/interfaces \
-			|| echo "auto $IFNAME" \
-			| sudo tee -a /etc/network/interfaces >/dev/null
-		sudo grep "iface $IFNAME inet dhcp" /etc/network/interfaces \
-			|| echo "iface $IFNAME inet dhcp" \
-			| sudo tee -a /etc/network/interfaces >/dev/null
 		(
 			printf %s\\n \
 				'auto lo' \
@@ -48,11 +52,13 @@ if exists iwctl; then
 					[ -e "$1/device" ] && printf %s " $(basename "$1")"
 				' -- \{\} \;
 			)
-			if [ "$#" -eq 1 ]; then
-				printf %s\\n \
-					"auto $1" \
-					"iface $1 inet dhcp" \
-					| sudo tee -a /etc/network/interfaces >/dev/null
+			if [ "$#" -eq 1 ] || ! apk info -e bonding >/dev/null; then
+				for interface in "$@"; do
+					printf %s\\n \
+						"auto $interface" \
+						"iface $interface inet dhcp" \
+						| sudo tee -a /etc/network/interfaces >/dev/null
+				done
 			else
 				printf %s\\n \
 					'auto bond0' \
@@ -61,12 +67,39 @@ if exists iwctl; then
 					| sudo tee -a /etc/network/interfaces >/dev/null
 			fi
 		)
-		sudo rc-update add -q iwd boot
-		sudo rc-service -q dbus start
-		sudo rc-service -q iwd restart
+		if rc-service --exists iwd && rc-service --exists dbus; then
+			if rc-service --exists wpa_supplicant; then
+				sudo rc-update del -q wpa_supplicant boot
+				sudo rc-service -q wpa_supplicant stop
+			fi
+			sudo rc-update add -q iwd boot
+			sudo rc-service -q dbus start
+			sudo rc-service -q iwd restart
+		elif rc-service --exists wpa_supplicant; then
+			sudo rc-update add -q wpa_supplicant boot
+			sudo rc-service -q wpa_supplicant restart
+			sudo rc-update add -q wpa_cli boot
+		else
+			sudo rc-update add networking boot
+		fi
 		sudo rc-service -q networking restart
+		i=0
+		until
+			ip route | grep -q '^default via [0-9.]* dev' || [ $i -ge 30 ]
+		do
+			echo "interface not up, will try again in 1 second" >&2
+			i="$(($i + 1))"
+			sleep 1
+		done
+
 	}
 elif exists netctl; then
+	export IFNAME="$(
+		find /sys/class/net -follow -maxdepth 2 -name phy80211 2>/dev/null \
+			| head \
+			| cut -d / -f 5
+	)"
+
 	install() {
 		awk '
 		function escape(str) {
@@ -102,7 +135,7 @@ else
 	die "Did not detect a known networking system"
 fi
 
-for cred in $WIFI_CREDENTIALS; do
+for cred in ${WIFI_CREDENTIALS-}; do
 	eval "$(echo "$cred" | awk -F\; '
 		function parsehex(h,  i, n, c) {
 			n = 0
diff --git a/PREFIX/src/roles/socat_tunnel b/PREFIX/src/roles/socat_tunnel
--- a/PREFIX/src/roles/socat_tunnel
+++ b/PREFIX/src/roles/socat_tunnel
@@ -2,7 +2,15 @@
 # shellcheck disable=SC2016,SC1003
 set -eu
 
-pacman --needed --noconfirm -qS socat
+exists() { command -v "$1" >/dev/null 2>&1; }
+
+exists systemctl || { printf "ERROR: requires systemd" >&2 && exit 1; }
+
+if exists apk; then
+	apk -q add socat
+elif exists pacman; then
+	pacman --needed --noconfirm -qS socat
+fi
 
 sudo systemd-tmpfiles --create - <<-EOF
 	f+~ /etc/systemd/system/tunnel@.service - - - - $(
diff --git a/XDG_BIN_HOME/write_os b/XDG_BIN_HOME/write_os
--- a/XDG_BIN_HOME/write_os
+++ b/XDG_BIN_HOME/write_os
@@ -3,15 +3,24 @@
 #write_os - write os to device/file
 set -eu
 
+escape() { echo "$1" | sed "s/'/'\\\\''/g"; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 device_of() { df -P "$1" | awk 'END { print $1 }'; }
 fnmatch() { case "$2" in $1) return 0 ;; *) return 1 ;; esac }
+in_dir() (cd "$1" && shift && "$@")
 to_argv() (
 	set +x
 	while read -r LINE; do set -- "$@" "$LINE"; done
 	"$@"
 )
+quote() {
+	for x; do
+		printf "'" && printf %s "$x" | sed "s/'/'\\\\''/g" && printf "' " \
+			|| return 1
+	done
+}
+sponge() { set -- "$1" "$(mktemp)" && cat >"$2" && sudo mv "$2" "$1"; }
 
 clean() {
 	sync
@@ -27,7 +36,7 @@ clean() {
 	if losetup --help 2>&1 | grep -q -e '--output'; then
 		losetup -nONAME -j "$FILE"
 	else
-		losetup -a \
+		{ losetup -a 2>/dev/null || :; } \
 			| awk -vpath="$FILE" '
 				{
 					if (index($0, path))
@@ -51,6 +60,20 @@ download() { #1: url, 2: path
 	fi
 }
 
+uname_to_arch() {
+	case "$(uname -m)" in
+	x86_64) echo x86_64 ;;
+	aarch64 | arm64) echo aarch64 ;;
+	armv7l) echo armv7 ;;
+	armv6l) echo armhf ;;
+	i?86) echo x86 ;;
+	esac
+}
+
+distro_id() {
+	cat /etc/os-release 2>/dev/null | sed -En 's/^ID="?(.*)"?$/\1/p'
+}
+
 get_rpi_image() { #1: version
 	set -- "$(echo "$ARCH" | sed 's/armv6//')"
 	set -- "rpi${1:+-$1}"
@@ -61,7 +84,7 @@ get_rpi_image() { #1: version
 }
 
 get_dev_for() { #1: path
-	mount | sed -n 's_\(/dev/[^ ]*\) on '"$1"' .*_\1_p'
+	mount | sed -n 's|\(/dev/[^ ]*\) on '"$1"' .*|\1|p'
 }
 
 crude_wipefs() { #1: dev
@@ -71,6 +94,11 @@ crude_wipefs() { #1: dev
 }
 
 create_root() { #1: device 2: root 3: disklabel 4?: size
+	if exists apk; then
+		apk add e2fsprogs sfdisk
+	elif exists pacman; then
+		sudo pacman --needed --noconfirm -qS e2fsprogs dosfstools
+	fi
 	mkfs.vfat --help >/dev/null 2>&1 || die "error: install mkfs.vfat"
 	mkfs.ext4 2>&1 | grep -q Usage || die "error: install mkfs.ext4"
 
@@ -101,7 +129,8 @@ create_root() { #1: device 2: root 3: disklabel 4?: size
 		case "$3" in
 		dos)
 			exists fdisk || die "error: install sfdisk or fdisk"
-			echo 'o; n;p;1;;+1G; t;c; n;p;2;;8G; t;2;82;  n;p;3;;; w;q;' \
+			#echo 'o; n;p;1;;+1G; t;c; n;p;2;;+8G; t;2;82;  n;p;3;;; w;q;' \
+			echo 'o; n;p;1;;+1G; t;c; n;p;2;;; w;q;' \
 				| tr -d \  | tr ';' '\n' \
 				| sudo fdisk "$1" || true #Maybe rereading part table failed
 			;;
@@ -141,6 +170,41 @@ create_root() { #1: device 2: root 3: disklabel 4?: size
 	[ -d "$2" ] && [ -d "$2/boot" ] || die "error: fs setup/mount failed"
 }
 
+ALPINE_REMOTE=https://dl-cdn.alpinelinux.org/alpine
+[ "$(id -u)" = 0 ] \
+	&& ALPINE_LOCAL="/usr/local/share/alpine-repo" \
+	|| ALPINE_LOCAL="$XDG_CACHE_HOME/alpine-repo"
+
+alpine_version_to_branch() { #1?: version
+	[ $# -eq 1 ] || set -- "$(cat /etc/alpine-release)"
+	case "$1" in
+	*.*.*) set -- "${1%.*}" && echo "v${1#v}" ;;
+	*) echo edge ;;
+	esac
+}
+
+repo_location() { #1: root 2: repo 3: file
+	printf "%s/%s/%s/%s%s" "$1" "$ALPINE_BRANCH" "$2" "$ARCH" "${3+/$3}"
+}
+
+apk_dl() { #1: repo 2: file
+	mkdir -p "$(dirname "$(repo_location "$ALPINE_LOCAL" "$@")")"
+	download \
+		"$(repo_location "$ALPINE_REMOTE" "$@")" \
+		"$(repo_location "$ALPINE_LOCAL" "$@")" \
+		|| return 1
+	repo_location "$ALPINE_LOCAL" "$@"
+}
+
+#apk_dl_pkg() { #1: repo 2: name
+#    set -- "$1" "$2" "$(apk_dl "$1" APKINDEX.tar.gz)"
+#    set -- "$1" "$2" "$3" "$(tar -xOf "$3" | awk '
+#        /^P:'"$2"'$/ { found=1 }
+#        found && /^V:/ { print substr($0,3); exit }
+#    ')"
+#    apk_dl "$1" "$2-$4.apk"
+#}
+
 cp_dot() { #1: new_home 2: destdir
 	sudo mkdir -p "${2-}$1/.local/dot"
 	DOTFILES="$(
@@ -165,6 +229,167 @@ cp_dot() { #1: new_home 2: destdir
 			i="${i#./}"; f="$(printenv "${i%%/*}")/${i#*/}" || continue; \
 			mkdir -p "$dest${f%/*}"; ln -fs "$HOME/.local/dot/$i" "$dest$f"; \
 		done' -- {} +
+}
+
+write_customization() {
+	sudo mkdir -p "$ROOT/etc"
+	sudo touch "$ROOT/etc/.default_boot_services"
+	sudo mkdir -p "$ROOT/etc/runlevels/default"
+	sudo ln -sf /etc/init.d/local "$ROOT/etc/runlevels/default"
+	cp_dot "/root" "$ROOT"
+	cp_dot "/home/mil" "$ROOT"
+
+	sudo mkdir -p "$ROOT/etc/local.d"
+	printf '%s\n' \
+		'#!/bin/sh' \
+		'set -eux' \
+		'' \
+		'exec </dev/null >>/var/log/local-provisioning.log 2>&1' \
+		'cd /root/.local/dot/PREFIX/src/roles' \
+		'' \
+		| sudo tee "$ROOT/etc/local.d/init.start" >/dev/null
+	[ $# -gt 0 ] || set -- \
+		-s init \
+		-s sysusers \
+		-s apk_wrapped \
+		-s networking \
+		-s ntp \
+		-e FOR_USER=mil -s home
+	while getopts 's:e:c:' OPT "$@"; do
+		case "$OPT" in
+		s)
+			[ ! -e "$ROOT/root/.local/dot/PREFIX/src/roles/$OPTARG/script" ] \
+				|| OPTARG="$OPTARG/script"
+			printf 'sh -x %s\n' "$OPTARG" \
+				| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
+			;;
+		e)
+			printf 'export %s='\''%s'\''\n' "${OPTARG%%=*}" \
+				"$(escape "${OPTARG#*=}")" \
+				| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
+			;;
+		c)
+			printf '%s\n' "${OPTARG}" \
+				| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
+			;;
+		*) die "ERROR: Unknown option: %OPT" ;;
+		esac
+	done
+	shift $((OPTIND - 1)) && OPTIND=1
+
+	printf '%s\n' \
+		'' \
+		'rm /etc/local.d/init.start' \
+		| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
+	sudo chmod +x "$ROOT/etc/local.d/init.start"
+
+	printf "%s" "$HOSTNAME" | sudo tee "$ROOT/etc/hostname" >/dev/null
+
+	if exists apk; then
+		(
+			set -- \
+				alpine-base abuild doas-sudo-shim \
+				iwd iwd-openrc bonding dbus dbus-openrc rsync \
+				curl git git-perl gnupg make ncurses zsh ncurses-terminfo
+			#Due to the SD card unmount
+			! fnmatch 'rpi*' "$HARDWARE" \
+				|| set -- "$@" linux-rpi raspberrypi-bootloader \
+					alpine-base openssh openssl dosfstools e2fsprogs
+			apk_repofetch -m "$ARCH" -b "$ALPINE_BRANCH" "$@"
+			apk_repofetch -m "$ARCH" -b "$ALPINE_BRANCH" -p "$ROOT" "$@"
+		)
+	fi
+}
+
+write_distro_alpine() {
+	if
+		[ "$ARCH" = "$(uname_to_arch)" ] && [ "$(distro_id)" = alpine ] \
+			&& [ "$HARDWARE" != live ]
+	then
+		ALPINE_VERSION="$(cat /etc/alpine-release)}"
+		ALPINE_BRANCH="$(alpine_version_to_branch "$ALPINE_VERSION")"
+		SOURCE=self
+	else
+		ALPINE_VERSION="${ALPINE_VERSION:-3.24.0}"
+		ALPINE_BRANCH="$(alpine_version_to_branch "$ALPINE_VERSION")"
+		SOURCE="$(
+			if fnmatch "rpi*" "$HARDWARE"; then
+				if [ "$(uname -s)" = Linux ]; then
+					apk_dl releases "alpine-rpi-$ALPINE_VERSION-$ARCH.tar.gz"
+				elif [ "$(uname -s)" = Darwin ]; then
+					apk_dl releases "alpine-rpi-$ALPINE_VERSION-$ARCH.img.gz"
+				fi
+			else
+				apk_dl releases "alpine-standard-$ALPINE_VERSION-$ARCH.iso"
+			fi
+		)"
+	fi
+	case "$SOURCE" in
+	self)
+		if
+			{ [ "$HARDWARE" = standard ] && [ ! -d /sys/firmware/efi ]; } \
+				|| fnmatch "rpi[1-4]" "$HARDWARE"
+		then
+			DISKLABEL="dos"
+		else
+			DISKLABEL="gpt"
+		fi
+		ROOT="$(mktemp -d)"
+		trap clean EXIT
+		if fnmatch "rpi*" "$HARDWARE" && mount | grep -q 'on /.modloop'; then
+			DO_UMOUNT=1 copy-modloop
+		fi
+		create_root "$FILE" "$ROOT" "$DISKLABEL" "${SIZE-16G}"
+		setup-disk "$ROOT"
+		[ "$DISKLABEL" = gpt ] \
+			|| fnmatch "rpi*" "$HARDWARE" \
+			|| (</usr/share/syslinux/mbr.bin sudo tee "$FILE" >/dev/null)
+		write_customization "$@"
+		;;
+	*.iso)
+		! exists apk || sudo apk add -q xorriso
+		ROOT="$(mktemp -d)"
+		trap clean EXIT
+		FILE="${FILE:-${SOURCE%.iso}.local.iso}"
+		write_customization "$@"
+		ROOTOVERLAY="$(mktemp)"
+		tar -czf "$ROOTOVERLAY" -C "$ROOT" .
+		if [ -b "$FILE" ]; then
+			BACKING_FILE="$FILE"
+			FILE="$(mktemp)"
+		else
+			sudo rm -f "$FILE"
+		fi
+		#if [ -b "$FILE" ]; then
+		#    sudo wipefs -a "$FILE"
+		#else
+		#    sudo rm -f "$FILE"
+		#fi
+		sudo xorriso -indev "$SOURCE" -outdev "stdio:$FILE" \
+			-boot_image any replay -map "$ROOTOVERLAY" /localhost.apkovl.tar.gz
+		if [ -n "${BACKING_FILE-}" ]; then
+			dd if="$FILE" of="$BACKING_FILE"
+			rm "$FILE"
+		else
+			sudo chown "$(whoami)" "$FILE"
+		fi
+		rm "$ROOTOVERLAY"
+		;;
+	*.tar.gz)
+		trap clean EXIT
+		ROOT="$(mktemp -d)"
+		write_customization "$@"
+		ROOTOVERLAY="$(sudo mktemp)"
+		sudo tar -czf "$ROOTOVERLAY" -C "$ROOT" .
+		sudo rm -r "$ROOT"
+		ROOT="$(mktemp -d)"
+		DISKLABEL="$(fnmatch "rpi[1-4]" "$HARDWARE" && echo dos || echo gpt)"
+		FILE="${FILE:-${SOURCE%.tar.gz}.img}"
+		create_root "$FILE" "$ROOT" "$DISKLABEL" "${SIZE-16G}"
+		sudo tar --numeric-owner -xzf "$SOURCE" -C "$ROOT/boot"
+		sudo mv "$ROOTOVERLAY" "$ROOT/boot/localhost.apkovl.tar.gz"
+		;;
+	esac
 }
 
 write_distro_arch() {
@@ -200,7 +425,7 @@ write_distro_arch() {
 				&& sudo mv "$ROOT/etc/fstab.new" "$ROOT/etc/fstab"
 		fi
 	else
-		if [ "$HARDWARE" = usb ]; then
+		if [ "$HARDWARE" = live ]; then
 			sudo pacman --needed --noconfirm -S archiso
 			</usr/share/archiso/configs/releng/packages.x86_64 grep \
 				-vE '^(#|grml-zsh-config)' \
@@ -236,12 +461,15 @@ write_distro_arch() {
 }
 
 write_os() {
-	while getopts h:m:f:s: OPT "$@"; do
+	while getopts h:m:n:d:f:s:r OPT "$@"; do
 		case "$OPT" in
 		h) HARDWARE="$OPTARG" ;;
-		m) ARCH="$OPTARG" ;; #Same as uname
+		m) ARCH="$OPTARG" ;;     #Same as uname
+		n) HOSTNAME="$OPTARG" ;; #Same as uname
+		d) DISTRO="$OPTARG" ;;
 		f) FILE="$OPTARG" ;;
 		s) SIZE="$OPTARG" ;;
+		r) RUN=true ;;
 		*) printf "ERROR: Unknown option: %s" "$OPT" >&2 && return 1 ;;
 		esac
 	done
@@ -253,8 +481,10 @@ write_os() {
 				</sys/firmware/devicetree/base/model tr -d '\0' \
 					| sed -E 's/Raspberry Pi ([0-9]).*/rpi\1/'
 			)"
-		else
+		elif fnmatch '/dev/nvme*' "$FILE"; then
 			HARDWARE=standard
+		else
+			HARDWARE=live
 		fi
 	fi
 	if [ -z "${ARCH-}" ]; then
@@ -262,10 +492,28 @@ write_os() {
 		rpi1) ARCH=armhf ;;
 		rpi2) ARCH=armv7 ;;
 		rpi[345]) ARCH=aarch64 ;;
-		standard) ARCH=x86_64 ;;
+		live) ARCH=x86_64 ;;
+		standard) ARCH="$(uname_to_arch)" ;;
 		esac
 	fi
-	write_distro_arch
+	DISTRO="${DISTRO-alpine}"
+	case "$DISTRO" in
+	alpine) write_distro_alpine "$@" ;;
+	arch) write_distro_arch "$@" ;;
+	esac
+	if
+		[ "${RUN-}" = true ] && [ "$ARCH" = x86_64 ] \
+			&& [ "$(uname_to_arch)" = x86_64 ]
+	then
+		STTY_SETTINGS="$(stty -g)"
+		qemu-system-x86_64 -m 5120 -nic user -boot order=d \
+			-drive if=ide,media=disk,format=raw,file="${BACKING_FILE-$FILE}" \
+			-enable-kvm -display none \
+			-chardev stdio,id=serial0,signal=off \
+			-serial chardev:serial0 -monitor none
+		stty "$STTY_SETTINGS"
+		tput smam
+	fi
 }
 
 write_os "$@"
