Format most that is supported by shfmt

diff --git a/XDG_BIN_HOME/imgrename b/XDG_BIN_HOME/imgrename
--- a/XDG_BIN_HOME/imgrename
+++ b/XDG_BIN_HOME/imgrename
@@ -5,11 +5,11 @@ set -eu
 timestamp() { #1: file
     #exiv2 -Pv -K Exif.Photo.DateTimeOriginal "$1" 2>/dev/null
     case "$1" in
-    *.JPG|*.jpg|*.ORF|*.orf)
-        exiftool -DateTimeOriginal "$1"\
+    *.JPG | *.jpg | *.ORF | *.orf)
+        exiftool -DateTimeOriginal "$1" \
             | sed 's/.*\(....\):\(..\):\(..\) \(..:..:..\)/\1-\2-\3T\4/'
         ;;
-    *.MOV|*.mov)
+    *.MOV | *.mov)
         exiftool -CreateDate "$1" \
             | sed 's/.*\(....\):\(..\):\(..\) \(..:..:..\)/\1-\2-\3T\4/'
         ;;
@@ -28,7 +28,8 @@ for x; do
     newname="$(timestamp "$x")_$(serial "$x").$(extension "$x")"
     if [ "$x" != "$newname" ]; then
         if [ -x "$newname" ]; then
-            echo "error: $x: target $newname exists" >&2; exit 1
+            echo "error: $x: target $newname exists" >&2
+            exit 1
         fi
         mv "$x" "$newname"
     fi
diff --git a/XDG_BIN_HOME/matrix_client b/XDG_BIN_HOME/matrix_client
--- a/XDG_BIN_HOME/matrix_client
+++ b/XDG_BIN_HOME/matrix_client
@@ -5,18 +5,18 @@ set -eu
 isodate() {
     if [ "${#2}" -eq 1 ]; then set -- "$1" "0$2"; fi
     case "$1" in
-    Jan) echo "01-$2";;
-    Feb) echo "02-$2";;
-    Mar) echo "03-$2";;
-    Apr) echo "04-$2";;
-    May) echo "05-$2";;
-    Jun) echo "06-$2";;
-    Jul) echo "07-$2";;
-    Aug) echo "08-$2";;
-    Sep) echo "09-$2";;
-    Oct) echo "10-$2";;
-    Nov) echo "11-$2";;
-    Dec) echo "12-$2";;
+    Jan) echo "01-$2" ;;
+    Feb) echo "02-$2" ;;
+    Mar) echo "03-$2" ;;
+    Apr) echo "04-$2" ;;
+    May) echo "05-$2" ;;
+    Jun) echo "06-$2" ;;
+    Jul) echo "07-$2" ;;
+    Aug) echo "08-$2" ;;
+    Sep) echo "09-$2" ;;
+    Oct) echo "10-$2" ;;
+    Nov) echo "11-$2" ;;
+    Dec) echo "12-$2" ;;
     esac
 }
 
@@ -24,27 +24,32 @@ daemon() {
     if ! pgrep -f "mpmc -d $MPMC_HOME" >/dev/null 2>&1; then
         mkdir -p "$MPMC_HOME"
         (mpmc -d "$MPMC_HOME" \
-            -s "$(pass show web/chat.eforah.nl | sed -n 's/^homeserver: //p')"\
+            -s "$(pass show web/chat.eforah.nl | sed -n 's/homeserver: //p')" \
             -u "$(pass show web/chat.eforah.nl | sed -n 's/^user: //p')" \
             -p 'pass show web/chat.eforah.nl|head -n1' \
             >"$MPMC_HOME/out" 2>>"$MPMC_HOME/log" </dev/null &)
         while ! [ -n "$(find $XDG_DATA_HOME/mpmc -mindepth 1 -type d)" ]; do
             sleep 1
             if ! pgrep -f "mpmc -d $MPMC_HOME" >/dev/null 2>&1; then
-                echo "matrix_client: couldn't start daemon" >&2; exit 1;
+                echo "matrix_client: couldn't start daemon" >&2
+                exit 1
             fi
         done
     fi
-    ROOMS="$(\
-        for x in "$MPMC_HOME"/*/*/\!*; do \
-            echo "$(basename "$x") $(cat "$x/name" 2>/dev/null)"; \
-        done | sed '/[^ ] $/d')"
+    ROOMS="$(
+        for x in "$MPMC_HOME"/*/*/\!*; do
+            echo "$(basename "$x") $(cat "$x/name" 2>/dev/null)"
+        done | sed '/[^ ] $/d'
+    )"
 }
 
 send() {
     daemon
     mkdir -p "$XDG_CACHE_HOME/mpmc"
-    SERVER="$(cd "$MPMC_HOME"; find . -mindepth 2 -maxdepth 2 -type d |fzf -1)"
+    SERVER="$(
+        cd "$MPMC_HOME"
+        find . -mindepth 2 -maxdepth 2 -type d | fzf -1
+    )"
     SENDER="$(echo "$SERVER" | sed 's|.*/@\([^:]*\).*|\1|')"
     CROOM="$(cat "$XDG_CACHE_HOME/mpmc/room" 2>/dev/null || true)"
     ROOM="$(echo "$ROOMS" | cut -d" " -f2- \
@@ -70,14 +75,18 @@ view() {
 }
 
 print() { #1: notify
-    CDATE="${CDATE:-$(date '+%h %-d')}"; CROOM="${CROOM:-}"
+    CDATE="${CDATE:-$(date '+%h %-d')}"
+    CROOM="${CROOM:-}"
     COLUMNS="${COLUMNS:-$(tput cols)}"
     while read -r MODE LINKS USER GROUP SIZE MONTH DAY TIME FILE; do
         DATE="$MONTH $DAY"
         MSGID="${FILE##*/}"
-        SENDER="${FILE%%/$MSGID}"; SENDER="${SENDER##*/}"
-        ROOMID="${FILE%%/$SENDER/$MSGID}"; ROOMID="${ROOMID##*/}"
-        SENDER="${SENDER##@}"; SENDER="${SENDER%%:*}"
+        SENDER="${FILE%%/$MSGID}"
+        SENDER="${SENDER##*/}"
+        ROOMID="${FILE%%/$SENDER/$MSGID}"
+        ROOMID="${ROOMID##*/}"
+        SENDER="${SENDER##@}"
+        SENDER="${SENDER%%:*}"
         CONTENT="$(cat "$FILE")"
         if [ "$DATE" != "$CDATE" ] || [ "$ROOMID" != "$CROOM" ]; then
             printf "%s \e[4m%s\e[0m\n" \
@@ -85,18 +94,22 @@ print() { #1: notify
                 "$(echo "$ROOMS" | sed -n "s/^$ROOMID //p")"
         fi
         if [ "$SENDER" = p64protocolbot ]; then
-            SENDER="$(<"$FILE" read -r p || :; p="${p%%>*}"; echo "${p##*<@}")"
+            SENDER="$(
+                <"$FILE" read -r p || :
+                p="${p%%>*}"
+                echo "${p##*<@}"
+            )"
             CONTENT="${CONTENT#*> }"
         fi
         if "${1:-false}"; then
             notify-send "$SENDER" "$CONTENT"
         fi
         case "$SENDER" in
-        ?????????*) SENDER="${SENDER%${SENDER#????????}}…";;
+        ?????????*) SENDER="${SENDER%${SENDER#????????}}…" ;;
         esac
         printf "\033[2m%s \033[1m%s\t\033[0m%s\n" "$TIME" "$SENDER" \
             "$(echo "$CONTENT" \
-                | fold -sw $(( $COLUMNS - 16 )) \
+                | fold -sw $(($COLUMNS - 16)) \
                 | sed '/^$/d;2,$s/^/'"$(printf "\t\t")"'/')"
         CDATE="$DATE"
         CROOM="$ROOMID"
diff --git a/XDG_BIN_HOME/notify-send b/XDG_BIN_HOME/notify-send
--- a/XDG_BIN_HOME/notify-send
+++ b/XDG_BIN_HOME/notify-send
@@ -1,33 +1,43 @@
 #!/usr/bin/env sh
 set -eu
 
-die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi; exit 1; }
+die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
 
 to_hint() {
-    set -- "${1%%:*}" "${1#*:}"; set -- "$1" "${2%%:*}" "${2#*:}"
+    set -- "${1%%:*}" "${1#*:}"
+    set -- "$1" "${2%%:*}" "${2#*:}"
     case "$1" in
-    int|INT|int32) printf '"%s": <int32 %s>' "$2" "$3";;
-    double|DOUBLE) printf '"%s": <double %s>';;
-    byte|BYTE) printf '"%s": <byte %s>';;
-    string|STRING) printf '"%s": <string "%s">';;
-    *) die "Invalid type: '$1'. Did you set a valid TYPE:NAME:VALUE hint?";;
+    int | INT | int32) printf '"%s": <int32 %s>' "$2" "$3" ;;
+    double | DOUBLE) printf '"%s": <double %s>' ;;
+    byte | BYTE) printf '"%s": <byte %s>' ;;
+    string | STRING) printf '"%s": <string "%s">' ;;
+    *) die "Invalid type: '$1'. Did you set a valid TYPE:NAME:VALUE hint?" ;;
     esac
 }
 
 notify_send_dbus() {
     while getopts u:t:i:c:h:pr:R: OPT "$@"; do
         case "$OPT" in
-        u) case "$OPTARG" in low) u=0;; normal) u=1;; critical) u=2;; esac;;
-        t) expire="$OPTARG";;
-        i) icon="$OPTARG";;
-        c) hint="${hint:-}$(to_hint string:category:"$OPTARG"), ";;
-        h) hint="${hint:-}$(to_hint "$OPTARG"), ";;
-        p) rfile="/dev/stdout";;
-        r) rid="$OPTARG";;
-        R) rfile="$OPTARG"; ! [ -f "$rfile" ] || <"$rfile" read rid ||:;;
+        u)
+            case "$OPTARG" in
+            low) u=0 ;;
+            normal) u=1 ;;
+            critical) u=2 ;;
+            esac
+            ;;
+        t) expire="$OPTARG" ;;
+        i) icon="$OPTARG" ;;
+        c) hint="${hint:-}$(to_hint string:category:"$OPTARG"), " ;;
+        h) hint="${hint:-}$(to_hint "$OPTARG"), " ;;
+        p) rfile="/dev/stdout" ;;
+        r) rid="$OPTARG" ;;
+        R)
+            rfile="$OPTARG"
+            ! [ -f "$rfile" ] || <"$rfile" read rid || :
+            ;;
         esac
     done
-    shift $(( $OPTIND - 1 ))
+    shift $(($OPTIND - 1))
     gdbus call --session --object-path /org/freedesktop/Notifications \
         --dest org.freedesktop.Notifications \
         --method org.freedesktop.Notifications.Notify \
@@ -36,15 +46,18 @@ notify_send_dbus() {
         "{${hint:-}$(to_hint int:urgency:${urg:-1})}" \
         "int32 ${expire:--1}" \
         | sed 's/(uint32 \([0-9]*\),)/\1/' \
-        >"${rfile:-/dev/null}"
+            >"${rfile:-/dev/null}"
 }
 
 notify_send_macos() {
     while case "$1" in
-        --) shift; false;;
-        -*) shift;;
-        *) false;;
-    esac; do :; done
+        --)
+            shift
+            false
+            ;;
+        -*) shift ;;
+        *) false ;;
+        esac do :; done
 
     export title="$([ -n "${2:-}" ] && echo "$1" \
         || echo "$(ps -o comm= $PPID)")"
@@ -56,9 +69,9 @@ notify_send_macos() {
 
 notify_send() {
     case "$(uname -s)" in
-        Darwin) notify_send_macos "$@" ;;
-        Linux) notify_send_dbus "$@" ;;
-        *) die "Unsupported notification system" ;;
+    Darwin) notify_send_macos "$@" ;;
+    Linux) notify_send_dbus "$@" ;;
+    *) die "Unsupported notification system" ;;
     esac
 }
 
