Change usb_img interface to use getopts

diff --git a/XDG_BIN_HOME/write_os b/XDG_BIN_HOME/write_os
--- a/XDG_BIN_HOME/write_os
+++ b/XDG_BIN_HOME/write_os
@@ -23,7 +23,7 @@ clean() {
 			shift 2
 		done
 	)
-	losetup -nONAME -j "$DEVICE" | xargs -rn1 sudo losetup -d
+	losetup -nONAME -j "$FILE" | xargs -rn1 sudo losetup -d
 	sudo rmdir "$ROOT"
 }
 
@@ -40,21 +40,8 @@ download() { #1: url, 2: path
 	fi
 }
 
-get_target_arch() {
-	case "$1" in
-	rpi1) echo armv6 ;;
-	rpi2) echo armv7 ;;
-	rpi3) echo aarch64 ;;
-	rpi4) echo aarch64 ;;
-	rpi5) echo aarch64 ;;
-	usb) echo x86_64 ;;
-	xps13) echo x86_64 ;;
-	server) echo x86_64 ;;
-	esac
-}
-
 get_rpi_image() { #1: version
-	set -- "$(get_target_arch "$1" | sed 's/armv6//')"
+	set -- "$(echo "$ARCH" | sed 's/armv6//')"
 	set -- "rpi${1:+-$1}"
 	set -- "http://os.archlinuxarm.org/os/ArchLinuxARM-${1}-latest.tar.gz"
 	set -- "$1" "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/${1##*/}"
@@ -66,11 +53,17 @@ get_dev_for() { #1: path
 	mount | sed -n 's_\(/dev/[^ ]*\) on '"$1"' .*_\1_p'
 }
 
-create_root() { #1: device 2: root 3: disklabel
+create_root() { #1: device 2: root 3: disklabel 4?: size
 	mkfs.vfat --help >/dev/null 2>&1 || die "error: install mkfs.vfat"
 	mkfs.ext4 2>&1 | grep -q Usage || die "error: install mkfs.ext4"
 	sgdisk --help >/dev/null 2>&1 || die "error: install sgdisk"
 
+	if [ ! -b "$1" ]; then
+		sudo modprobe loop
+		truncate -s "$4" "$1"
+		set -- "$(sudo losetup -fP --show "$1")" "$2" "$3" "${4:-}"
+		expr "$1" : /dev/ >/dev/null || die "error: loopback setup failed"
+	fi
 	sudo wipefs -a "$1"
 	case "$3" in
 	dos)
@@ -101,26 +94,19 @@ create_root() { #1: device 2: root 3: disklabel
 	[ -d "$2" ] && [ -d "$2/boot" ] || die "error: fs setup/mount failed"
 }
 
-write_os() { #1: path #2: target
-	[ $# -ge 2 ] \
-		|| die "usage: write_os DEVPATH HARDWARE [SIZE (only if loop device)]"
+write_distro_arch() {
 	ROOT="$(mktemp -d)"
-	DEVICE="$1"
 	trap clean EXIT
-	HARDWARE="$2"
-	if [ $# -eq 3 ] && [ ! -b "$1" ]; then
-		sudo modprobe loop
-		truncate -s "$3" "$1"
-		set -- "$(sudo losetup -fP --show "$1")" "$2"
-		expr "$1" : /dev/ || die "error: loopback setup failed"
-	fi
-	create_root "$1" "$ROOT" \
-		"$(fnmatch "rpi[1-4]" "$HARDWARE" && echo dos || echo gpt)"
+	create_root "$FILE" "$ROOT" \
+		"$(fnmatch "rpi[1-4]" "$HARDWARE" && echo dos || echo gpt)" \
+		"${SIZE-16G}"
+
 	if [ "${HARDWARE%[1-5]}" = rpi ]; then
 		echo "Actually downloading/writing data. This may take a while..." >&2
-		sudo tar -xpf "$(get_rpi_image "$2")" -C "$ROOT"
-		[ "$2" != rpi4 ] || sudo sed -i 's/mmcblk0/mmcblk1/g' "$ROOT/etc/fstab"
-		if [ "$2" = rpi5 ]; then
+		sudo tar -xpf "$(get_rpi_image "$HARDWARE")" -C "$ROOT"
+		[ "$HARDWARE" != rpi4 ] \
+			|| sudo sed -i 's/mmcblk0/mmcblk1/g' "$ROOT/etc/fstab"
+		if [ "$HARDWARE" = rpi5 ]; then
 			download http://mirror.archlinuxarm.org/aarch64/core/$(
 			)linux-rpi-6.6.28-1-aarch64.pkg.tar.xz \
 				"${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/linux-rpi.pkg.tar.xz"
@@ -152,7 +138,7 @@ write_os() { #1: path #2: target
 		fi
 	fi
 	genfstab -U "$ROOT" | sudo tee "$ROOT/etc/fstab" >/dev/null
-	if [ "$(get_target_arch "$2")" = "$(uname -m)" ]; then
+	if [ "$ARCH" = "$(uname -m)" ]; then
 		sudo cp -rL --preserve=mode \
 			"${DOTFILES-$PREFIX/dot}/PREFIX/src/roles" "$ROOT/usr/local/src"
 		sudo arch-chroot "$ROOT" sh -euc '
@@ -174,6 +160,39 @@ write_os() { #1: path #2: target
 			. /usr/local/src/roles/home
 		'
 	fi
+}
+
+write_os() {
+	while getopts h:m:f:s: OPT "$@"; do
+		case "$OPT" in
+		h) HARDWARE="$OPTARG" ;;
+		m) ARCH="$OPTARG" ;; #Same as uname
+		f) FILE="$OPTARG" ;;
+		s) SIZE="$OPTARG" ;;
+		*) printf "ERROR: Unknown option: %s" "$OPT" >&2 && return 1 ;;
+		esac
+	done
+	shift $((OPTIND - 1)) && OPTIND=1
+	[ -n "${FILE:-}" ] || die "Specify a device/file with -f FILE"
+	if [ -z "${HARDWARE-}" ]; then
+		if [ -e /sys/firmware/devicetree/base/model ]; then
+			HARDWARE="$(
+				</sys/firmware/devicetree/base/model tr -d '\0' \
+					| sed -E 's/Raspberry Pi ([0-9]).*/rpi\1/'
+			)"
+		else
+			HARDWARE=standard
+		fi
+	fi
+	if [ -z "${ARCH-}" ]; then
+		case "$HARDWARE" in
+		rpi1) ARCH=armhf ;;
+		rpi2) ARCH=armv7 ;;
+		rpi[345]) ARCH=aarch64 ;;
+		standard) ARCH=x86_64 ;;
+		esac
+	fi
+	write_distro_arch
 }
 
 write_os "$@"
